// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: admin_template.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminTemplateService_PublishTemplate_FullMethodName   = "/bobobeads.AdminTemplateService/PublishTemplate"
	AdminTemplateService_UnpublishTemplate_FullMethodName = "/bobobeads.AdminTemplateService/UnpublishTemplate"
	AdminTemplateService_GetPublishStatus_FullMethodName  = "/bobobeads.AdminTemplateService/GetPublishStatus"
)

// AdminTemplateServiceClient is the client API for AdminTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal admin template service - no HTTP gateway annotation.
// Authenticated only by service-to-service mTLS + scoped token.
type AdminTemplateServiceClient interface {
	PublishTemplate(ctx context.Context, in *PublishTemplateRequest, opts ...grpc.CallOption) (*PublishTemplateResponse, error)
	UnpublishTemplate(ctx context.Context, in *UnpublishTemplateRequest, opts ...grpc.CallOption) (*UnpublishTemplateResponse, error)
	GetPublishStatus(ctx context.Context, in *GetPublishStatusRequest, opts ...grpc.CallOption) (*GetPublishStatusResponse, error)
}

type adminTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminTemplateServiceClient(cc grpc.ClientConnInterface) AdminTemplateServiceClient {
	return &adminTemplateServiceClient{cc}
}

func (c *adminTemplateServiceClient) PublishTemplate(ctx context.Context, in *PublishTemplateRequest, opts ...grpc.CallOption) (*PublishTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishTemplateResponse)
	err := c.cc.Invoke(ctx, AdminTemplateService_PublishTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminTemplateServiceClient) UnpublishTemplate(ctx context.Context, in *UnpublishTemplateRequest, opts ...grpc.CallOption) (*UnpublishTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpublishTemplateResponse)
	err := c.cc.Invoke(ctx, AdminTemplateService_UnpublishTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminTemplateServiceClient) GetPublishStatus(ctx context.Context, in *GetPublishStatusRequest, opts ...grpc.CallOption) (*GetPublishStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublishStatusResponse)
	err := c.cc.Invoke(ctx, AdminTemplateService_GetPublishStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminTemplateServiceServer is the server API for AdminTemplateService service.
// All implementations must embed UnimplementedAdminTemplateServiceServer
// for forward compatibility.
//
// Internal admin template service - no HTTP gateway annotation.
// Authenticated only by service-to-service mTLS + scoped token.
type AdminTemplateServiceServer interface {
	PublishTemplate(context.Context, *PublishTemplateRequest) (*PublishTemplateResponse, error)
	UnpublishTemplate(context.Context, *UnpublishTemplateRequest) (*UnpublishTemplateResponse, error)
	GetPublishStatus(context.Context, *GetPublishStatusRequest) (*GetPublishStatusResponse, error)
	mustEmbedUnimplementedAdminTemplateServiceServer()
}

// UnimplementedAdminTemplateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminTemplateServiceServer struct{}

func (UnimplementedAdminTemplateServiceServer) PublishTemplate(context.Context, *PublishTemplateRequest) (*PublishTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishTemplate not implemented")
}
func (UnimplementedAdminTemplateServiceServer) UnpublishTemplate(context.Context, *UnpublishTemplateRequest) (*UnpublishTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpublishTemplate not implemented")
}
func (UnimplementedAdminTemplateServiceServer) GetPublishStatus(context.Context, *GetPublishStatusRequest) (*GetPublishStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublishStatus not implemented")
}
func (UnimplementedAdminTemplateServiceServer) mustEmbedUnimplementedAdminTemplateServiceServer() {}
func (UnimplementedAdminTemplateServiceServer) testEmbeddedByValue()                              {}

// UnsafeAdminTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminTemplateServiceServer will
// result in compilation errors.
type UnsafeAdminTemplateServiceServer interface {
	mustEmbedUnimplementedAdminTemplateServiceServer()
}

func RegisterAdminTemplateServiceServer(s grpc.ServiceRegistrar, srv AdminTemplateServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminTemplateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminTemplateService_ServiceDesc, srv)
}

func _AdminTemplateService_PublishTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminTemplateServiceServer).PublishTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminTemplateService_PublishTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminTemplateServiceServer).PublishTemplate(ctx, req.(*PublishTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminTemplateService_UnpublishTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpublishTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminTemplateServiceServer).UnpublishTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminTemplateService_UnpublishTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminTemplateServiceServer).UnpublishTemplate(ctx, req.(*UnpublishTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminTemplateService_GetPublishStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublishStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminTemplateServiceServer).GetPublishStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminTemplateService_GetPublishStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminTemplateServiceServer).GetPublishStatus(ctx, req.(*GetPublishStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminTemplateService_ServiceDesc is the grpc.ServiceDesc for AdminTemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminTemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bobobeads.AdminTemplateService",
	HandlerType: (*AdminTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishTemplate",
			Handler:    _AdminTemplateService_PublishTemplate_Handler,
		},
		{
			MethodName: "UnpublishTemplate",
			Handler:    _AdminTemplateService_UnpublishTemplate_Handler,
		},
		{
			MethodName: "GetPublishStatus",
			Handler:    _AdminTemplateService_GetPublishStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_template.proto",
}
