// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ai_generation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIGenerationService_ListAIStyles_FullMethodName          = "/bobobeads.v1.AIGenerationService/ListAIStyles"
	AIGenerationService_CreateStyleGeneration_FullMethodName = "/bobobeads.v1.AIGenerationService/CreateStyleGeneration"
	AIGenerationService_GetStyleGeneration_FullMethodName    = "/bobobeads.v1.AIGenerationService/GetStyleGeneration"
	AIGenerationService_ListStyleGenerations_FullMethodName  = "/bobobeads.v1.AIGenerationService/ListStyleGenerations"
)

// AIGenerationServiceClient is the client API for AIGenerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI 风格生成服务。
type AIGenerationServiceClient interface {
	// 获取可用 AI 风格列表。
	ListAIStyles(ctx context.Context, in *ListAIStylesRequest, opts ...grpc.CallOption) (*ListAIStylesResponse, error)
	// 创建 AI 风格转换任务。
	CreateStyleGeneration(ctx context.Context, in *CreateStyleGenerationRequest, opts ...grpc.CallOption) (*CreateStyleGenerationResponse, error)
	// 获取 AI 风格转换任务详情。
	GetStyleGeneration(ctx context.Context, in *GetStyleGenerationRequest, opts ...grpc.CallOption) (*GetStyleGenerationResponse, error)
	// 获取 AI 风格转换任务列表。
	ListStyleGenerations(ctx context.Context, in *ListStyleGenerationsRequest, opts ...grpc.CallOption) (*ListStyleGenerationsResponse, error)
}

type aIGenerationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIGenerationServiceClient(cc grpc.ClientConnInterface) AIGenerationServiceClient {
	return &aIGenerationServiceClient{cc}
}

func (c *aIGenerationServiceClient) ListAIStyles(ctx context.Context, in *ListAIStylesRequest, opts ...grpc.CallOption) (*ListAIStylesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAIStylesResponse)
	err := c.cc.Invoke(ctx, AIGenerationService_ListAIStyles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIGenerationServiceClient) CreateStyleGeneration(ctx context.Context, in *CreateStyleGenerationRequest, opts ...grpc.CallOption) (*CreateStyleGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStyleGenerationResponse)
	err := c.cc.Invoke(ctx, AIGenerationService_CreateStyleGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIGenerationServiceClient) GetStyleGeneration(ctx context.Context, in *GetStyleGenerationRequest, opts ...grpc.CallOption) (*GetStyleGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStyleGenerationResponse)
	err := c.cc.Invoke(ctx, AIGenerationService_GetStyleGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIGenerationServiceClient) ListStyleGenerations(ctx context.Context, in *ListStyleGenerationsRequest, opts ...grpc.CallOption) (*ListStyleGenerationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStyleGenerationsResponse)
	err := c.cc.Invoke(ctx, AIGenerationService_ListStyleGenerations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIGenerationServiceServer is the server API for AIGenerationService service.
// All implementations must embed UnimplementedAIGenerationServiceServer
// for forward compatibility.
//
// AI 风格生成服务。
type AIGenerationServiceServer interface {
	// 获取可用 AI 风格列表。
	ListAIStyles(context.Context, *ListAIStylesRequest) (*ListAIStylesResponse, error)
	// 创建 AI 风格转换任务。
	CreateStyleGeneration(context.Context, *CreateStyleGenerationRequest) (*CreateStyleGenerationResponse, error)
	// 获取 AI 风格转换任务详情。
	GetStyleGeneration(context.Context, *GetStyleGenerationRequest) (*GetStyleGenerationResponse, error)
	// 获取 AI 风格转换任务列表。
	ListStyleGenerations(context.Context, *ListStyleGenerationsRequest) (*ListStyleGenerationsResponse, error)
	mustEmbedUnimplementedAIGenerationServiceServer()
}

// UnimplementedAIGenerationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIGenerationServiceServer struct{}

func (UnimplementedAIGenerationServiceServer) ListAIStyles(context.Context, *ListAIStylesRequest) (*ListAIStylesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAIStyles not implemented")
}
func (UnimplementedAIGenerationServiceServer) CreateStyleGeneration(context.Context, *CreateStyleGenerationRequest) (*CreateStyleGenerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStyleGeneration not implemented")
}
func (UnimplementedAIGenerationServiceServer) GetStyleGeneration(context.Context, *GetStyleGenerationRequest) (*GetStyleGenerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStyleGeneration not implemented")
}
func (UnimplementedAIGenerationServiceServer) ListStyleGenerations(context.Context, *ListStyleGenerationsRequest) (*ListStyleGenerationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStyleGenerations not implemented")
}
func (UnimplementedAIGenerationServiceServer) mustEmbedUnimplementedAIGenerationServiceServer() {}
func (UnimplementedAIGenerationServiceServer) testEmbeddedByValue()                             {}

// UnsafeAIGenerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIGenerationServiceServer will
// result in compilation errors.
type UnsafeAIGenerationServiceServer interface {
	mustEmbedUnimplementedAIGenerationServiceServer()
}

func RegisterAIGenerationServiceServer(s grpc.ServiceRegistrar, srv AIGenerationServiceServer) {
	// If the following call panics, it indicates UnimplementedAIGenerationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIGenerationService_ServiceDesc, srv)
}

func _AIGenerationService_ListAIStyles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAIStylesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIGenerationServiceServer).ListAIStyles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIGenerationService_ListAIStyles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIGenerationServiceServer).ListAIStyles(ctx, req.(*ListAIStylesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIGenerationService_CreateStyleGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStyleGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIGenerationServiceServer).CreateStyleGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIGenerationService_CreateStyleGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIGenerationServiceServer).CreateStyleGeneration(ctx, req.(*CreateStyleGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIGenerationService_GetStyleGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStyleGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIGenerationServiceServer).GetStyleGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIGenerationService_GetStyleGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIGenerationServiceServer).GetStyleGeneration(ctx, req.(*GetStyleGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIGenerationService_ListStyleGenerations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStyleGenerationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIGenerationServiceServer).ListStyleGenerations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIGenerationService_ListStyleGenerations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIGenerationServiceServer).ListStyleGenerations(ctx, req.(*ListStyleGenerationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIGenerationService_ServiceDesc is the grpc.ServiceDesc for AIGenerationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIGenerationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bobobeads.v1.AIGenerationService",
	HandlerType: (*AIGenerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAIStyles",
			Handler:    _AIGenerationService_ListAIStyles_Handler,
		},
		{
			MethodName: "CreateStyleGeneration",
			Handler:    _AIGenerationService_CreateStyleGeneration_Handler,
		},
		{
			MethodName: "GetStyleGeneration",
			Handler:    _AIGenerationService_GetStyleGeneration_Handler,
		},
		{
			MethodName: "ListStyleGenerations",
			Handler:    _AIGenerationService_ListStyleGenerations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai_generation.proto",
}
