// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_CHINESE    Language = 0
	Language_ENGLISH    Language = 1
	Language_RUSSIAN    Language = 2
	Language_VIETNAMESE Language = 3
	Language_PORTUGUESE Language = 4
	Language_INDONESIAN Language = 5
	Language_MALAY      Language = 6
	Language_THAI       Language = 7
	Language_FILIPINO   Language = 8
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "CHINESE",
		1: "ENGLISH",
		2: "RUSSIAN",
		3: "VIETNAMESE",
		4: "PORTUGUESE",
		5: "INDONESIAN",
		6: "MALAY",
		7: "THAI",
		8: "FILIPINO",
	}
	Language_value = map[string]int32{
		"CHINESE":    0,
		"ENGLISH":    1,
		"RUSSIAN":    2,
		"VIETNAMESE": 3,
		"PORTUGUESE": 4,
		"INDONESIAN": 5,
		"MALAY":      6,
		"THAI":       7,
		"FILIPINO":   8,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type Platform int32

const (
	Platform_PLATFORM_UNKNOWN     Platform = 0
	Platform_PLATFORM_IOS         Platform = 1
	Platform_PLATFORM_ANDROID     Platform = 2
	Platform_PLATFORM_MINIPROGRAM Platform = 3
	Platform_PLATFORM_WEB         Platform = 4
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_UNKNOWN",
		1: "PLATFORM_IOS",
		2: "PLATFORM_ANDROID",
		3: "PLATFORM_MINIPROGRAM",
		4: "PLATFORM_WEB",
	}
	Platform_value = map[string]int32{
		"PLATFORM_UNKNOWN":     0,
		"PLATFORM_IOS":         1,
		"PLATFORM_ANDROID":     2,
		"PLATFORM_MINIPROGRAM": 3,
		"PLATFORM_WEB":         4,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// 客户端设备信息。
type Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ipv4 点分十进制, 必须为终端真实 IP 地址。
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// User-Agent，来自 HTTP 头。
	UserAgent string `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// iOS 6.0 及以上的 IDFA。
	Idfa    string `protobuf:"bytes,3,opt,name=idfa,proto3" json:"idfa,omitempty"`
	IdfaMd5 string `protobuf:"bytes,4,opt,name=idfa_md5,json=idfaMd5,proto3" json:"idfa_md5,omitempty"`
	// Android 设备的 IMEI。
	Imei    string `protobuf:"bytes,5,opt,name=imei,proto3" json:"imei,omitempty"`
	ImeiMd5 string `protobuf:"bytes,6,opt,name=imei_md5,json=imeiMd5,proto3" json:"imei_md5,omitempty"`
	// Android 开放匿名设备标识。
	Oaid    string `protobuf:"bytes,7,opt,name=oaid,proto3" json:"oaid,omitempty"`
	OaidMd5 string `protobuf:"bytes,8,opt,name=oaid_md5,json=oaidMd5,proto3" json:"oaid_md5,omitempty"`
	// Android 系统标识。
	AndroidId string `protobuf:"bytes,9,opt,name=android_id,json=androidId,proto3" json:"android_id,omitempty"`
	// 设备类型：0-手机；1-平板；2-PC；3-互联网电视。
	DeviceType int32 `protobuf:"varint,10,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	// 设备品牌。
	Brand string `protobuf:"bytes,11,opt,name=brand,proto3" json:"brand,omitempty"`
	// 设备型号。
	Model string `protobuf:"bytes,12,opt,name=model,proto3" json:"model,omitempty"`
	// 操作系统：例如 1-Android；2-iOS。
	Os int32 `protobuf:"varint,13,opt,name=os,proto3" json:"os,omitempty"`
	// 操作系统版本。
	Osv string `protobuf:"bytes,14,opt,name=osv,proto3" json:"osv,omitempty"`
	// 网络环境：0-未识别；1-wifi；2-2G；3-3G；4-4G；5-5G。
	Network int32 `protobuf:"varint,15,opt,name=network,proto3" json:"network,omitempty"`
	// 网络运营商：0-未知；1-移动；2-联通；3-电信。
	Operator int32 `protobuf:"varint,16,opt,name=operator,proto3" json:"operator,omitempty"`
	// 屏幕宽度。
	Width int32 `protobuf:"varint,17,opt,name=width,proto3" json:"width,omitempty"`
	// 屏幕高度。
	Height int32 `protobuf:"varint,18,opt,name=height,proto3" json:"height,omitempty"`
	// 屏幕方向：0-未知；1-竖屏；2-横屏。
	Orientation int32       `protobuf:"varint,20,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Geo         *Device_Geo `protobuf:"bytes,21,opt,name=geo,proto3" json:"geo,omitempty"`
	// 已安装的应用列表。
	InstalledApp []string       `protobuf:"bytes,22,rep,name=installed_app,json=installedApp,proto3" json:"installed_app,omitempty"`
	Caids        []*Device_CAID `protobuf:"bytes,23,rep,name=caids,proto3" json:"caids,omitempty"`
	// 系统启动标识。
	BootMark string `protobuf:"bytes,24,opt,name=boot_mark,json=bootMark,proto3" json:"boot_mark,omitempty"`
	// 系统启动更新标识。
	UpdateMark string `protobuf:"bytes,25,opt,name=update_mark,json=updateMark,proto3" json:"update_mark,omitempty"`
	// MAC 地址。
	Mac string `protobuf:"bytes,26,opt,name=mac,proto3" json:"mac,omitempty"`
	// Android ID 的 MD5 值。
	AndroidIdMd5 string `protobuf:"bytes,27,opt,name=android_id_md5,json=androidIdMd5,proto3" json:"android_id_md5,omitempty"`
	// 终端真实 IPv6 地址。
	Ipv6     string           `protobuf:"bytes,28,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	UserInfo *Device_UserInfo `protobuf:"bytes,29,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	// iOS 设备初始化时间。
	BirthTime string `protobuf:"bytes,30,opt,name=birth_time,json=birthTime,proto3" json:"birth_time,omitempty"`
	// iOS 设备系统启动时间。
	BootTime string `protobuf:"bytes,31,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	// iOS 设备系统更新时间。
	UpdateTime string `protobuf:"bytes,32,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// iOS Vendor 标识。
	Idfv     string   `protobuf:"bytes,33,opt,name=idfv,proto3" json:"idfv,omitempty"`
	IdfvMd5  string   `protobuf:"bytes,34,opt,name=idfv_md5,json=idfvMd5,proto3" json:"idfv_md5,omitempty"`
	Language Language `protobuf:"varint,35,opt,name=language,proto3,enum=bobobeads.v1.Language" json:"language,omitempty"`
	// 时区。
	Timezone      string `protobuf:"bytes,36,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Device) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Device) GetIdfa() string {
	if x != nil {
		return x.Idfa
	}
	return ""
}

func (x *Device) GetIdfaMd5() string {
	if x != nil {
		return x.IdfaMd5
	}
	return ""
}

func (x *Device) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *Device) GetImeiMd5() string {
	if x != nil {
		return x.ImeiMd5
	}
	return ""
}

func (x *Device) GetOaid() string {
	if x != nil {
		return x.Oaid
	}
	return ""
}

func (x *Device) GetOaidMd5() string {
	if x != nil {
		return x.OaidMd5
	}
	return ""
}

func (x *Device) GetAndroidId() string {
	if x != nil {
		return x.AndroidId
	}
	return ""
}

func (x *Device) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *Device) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device) GetOs() int32 {
	if x != nil {
		return x.Os
	}
	return 0
}

func (x *Device) GetOsv() string {
	if x != nil {
		return x.Osv
	}
	return ""
}

func (x *Device) GetNetwork() int32 {
	if x != nil {
		return x.Network
	}
	return 0
}

func (x *Device) GetOperator() int32 {
	if x != nil {
		return x.Operator
	}
	return 0
}

func (x *Device) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Device) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Device) GetOrientation() int32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

func (x *Device) GetGeo() *Device_Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *Device) GetInstalledApp() []string {
	if x != nil {
		return x.InstalledApp
	}
	return nil
}

func (x *Device) GetCaids() []*Device_CAID {
	if x != nil {
		return x.Caids
	}
	return nil
}

func (x *Device) GetBootMark() string {
	if x != nil {
		return x.BootMark
	}
	return ""
}

func (x *Device) GetUpdateMark() string {
	if x != nil {
		return x.UpdateMark
	}
	return ""
}

func (x *Device) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Device) GetAndroidIdMd5() string {
	if x != nil {
		return x.AndroidIdMd5
	}
	return ""
}

func (x *Device) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *Device) GetUserInfo() *Device_UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *Device) GetBirthTime() string {
	if x != nil {
		return x.BirthTime
	}
	return ""
}

func (x *Device) GetBootTime() string {
	if x != nil {
		return x.BootTime
	}
	return ""
}

func (x *Device) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *Device) GetIdfv() string {
	if x != nil {
		return x.Idfv
	}
	return ""
}

func (x *Device) GetIdfvMd5() string {
	if x != nil {
		return x.IdfvMd5
	}
	return ""
}

func (x *Device) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_CHINESE
}

func (x *Device) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type RequestHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求令牌。
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 客户端平台：ios、android、miniprogram、web。
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// 客户端应用版本。
	AppVersion string `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	// 设备唯一标识。
	DeviceId string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// 客户端语言。
	Language string `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	// 设备身份标识。
	Device *Device `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	// 游客账号恢复凭证。由客户端安全随机生成；服务端仅保存带密钥的哈希值。
	GuestCredential string `protobuf:"bytes,7,opt,name=guest_credential,json=guestCredential,proto3" json:"guest_credential,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestHeader) Reset() {
	*x = RequestHeader{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeader) ProtoMessage() {}

func (x *RequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeader.ProtoReflect.Descriptor instead.
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *RequestHeader) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestHeader) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RequestHeader) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *RequestHeader) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RequestHeader) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RequestHeader) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *RequestHeader) GetGuestCredential() string {
	if x != nil {
		return x.GuestCredential
	}
	return ""
}

type ResponseHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 业务状态码。
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应提示信息。
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 请求链路追踪 ID。
	TraceId       string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseHeader) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseHeader) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseHeader) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type PageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码，从 1 开始。
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量。
	PageSize      int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 总记录数。
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 当前页码。
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量。
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 是否还有下一页。
	HasMore       bool `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *PageResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type Device_Geo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 纬度，范围 [-90.0, +90.0]。
	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	// 经度，范围 [-180.0, +180.0]。
	Lon           float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device_Geo) Reset() {
	*x = Device_Geo{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device_Geo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device_Geo) ProtoMessage() {}

func (x *Device_Geo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device_Geo.ProtoReflect.Descriptor instead.
func (*Device_Geo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Device_Geo) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Device_Geo) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

// 广协 CAID。
type Device_CAID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 与 caid 配套的版本，例如 "20201201"。
	Ver           string `protobuf:"bytes,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Caid          string `protobuf:"bytes,2,opt,name=caid,proto3" json:"caid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device_CAID) Reset() {
	*x = Device_CAID{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device_CAID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device_CAID) ProtoMessage() {}

func (x *Device_CAID) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device_CAID.ProtoReflect.Descriptor instead.
func (*Device_CAID) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Device_CAID) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *Device_CAID) GetCaid() string {
	if x != nil {
		return x.Caid
	}
	return ""
}

type Device_UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Age           int32                  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Gender        int32                  `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device_UserInfo) Reset() {
	*x = Device_UserInfo{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device_UserInfo) ProtoMessage() {}

func (x *Device_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device_UserInfo.ProtoReflect.Descriptor instead.
func (*Device_UserInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Device_UserInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Device_UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\fbobobeads.v1\"\x8b\t\n" +
	"\x06Device\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12\x12\n" +
	"\x04idfa\x18\x03 \x01(\tR\x04idfa\x12\x19\n" +
	"\bidfa_md5\x18\x04 \x01(\tR\aidfaMd5\x12\x12\n" +
	"\x04imei\x18\x05 \x01(\tR\x04imei\x12\x19\n" +
	"\bimei_md5\x18\x06 \x01(\tR\aimeiMd5\x12\x12\n" +
	"\x04oaid\x18\a \x01(\tR\x04oaid\x12\x19\n" +
	"\boaid_md5\x18\b \x01(\tR\aoaidMd5\x12\x1d\n" +
	"\n" +
	"android_id\x18\t \x01(\tR\tandroidId\x12\x1f\n" +
	"\vdevice_type\x18\n" +
	" \x01(\x05R\n" +
	"deviceType\x12\x14\n" +
	"\x05brand\x18\v \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\f \x01(\tR\x05model\x12\x0e\n" +
	"\x02os\x18\r \x01(\x05R\x02os\x12\x10\n" +
	"\x03osv\x18\x0e \x01(\tR\x03osv\x12\x18\n" +
	"\anetwork\x18\x0f \x01(\x05R\anetwork\x12\x1a\n" +
	"\boperator\x18\x10 \x01(\x05R\boperator\x12\x14\n" +
	"\x05width\x18\x11 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x12 \x01(\x05R\x06height\x12 \n" +
	"\vorientation\x18\x14 \x01(\x05R\vorientation\x12*\n" +
	"\x03geo\x18\x15 \x01(\v2\x18.bobobeads.v1.Device.GeoR\x03geo\x12#\n" +
	"\rinstalled_app\x18\x16 \x03(\tR\finstalledApp\x12/\n" +
	"\x05caids\x18\x17 \x03(\v2\x19.bobobeads.v1.Device.CAIDR\x05caids\x12\x1b\n" +
	"\tboot_mark\x18\x18 \x01(\tR\bbootMark\x12\x1f\n" +
	"\vupdate_mark\x18\x19 \x01(\tR\n" +
	"updateMark\x12\x10\n" +
	"\x03mac\x18\x1a \x01(\tR\x03mac\x12$\n" +
	"\x0eandroid_id_md5\x18\x1b \x01(\tR\fandroidIdMd5\x12\x12\n" +
	"\x04ipv6\x18\x1c \x01(\tR\x04ipv6\x12:\n" +
	"\tuser_info\x18\x1d \x01(\v2\x1d.bobobeads.v1.Device.UserInfoR\buserInfo\x12\x1d\n" +
	"\n" +
	"birth_time\x18\x1e \x01(\tR\tbirthTime\x12\x1b\n" +
	"\tboot_time\x18\x1f \x01(\tR\bbootTime\x12\x1f\n" +
	"\vupdate_time\x18  \x01(\tR\n" +
	"updateTime\x12\x12\n" +
	"\x04idfv\x18! \x01(\tR\x04idfv\x12\x19\n" +
	"\bidfv_md5\x18\" \x01(\tR\aidfvMd5\x122\n" +
	"\blanguage\x18# \x01(\x0e2\x16.bobobeads.v1.LanguageR\blanguage\x12\x1a\n" +
	"\btimezone\x18$ \x01(\tR\btimezone\x1a)\n" +
	"\x03Geo\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x1a,\n" +
	"\x04CAID\x12\x10\n" +
	"\x03ver\x18\x01 \x01(\tR\x03ver\x12\x12\n" +
	"\x04caid\x18\x02 \x01(\tR\x04caid\x1a4\n" +
	"\bUserInfo\x12\x10\n" +
	"\x03age\x18\x01 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\x05R\x06gender\"\xf4\x01\n" +
	"\rRequestHeader\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12,\n" +
	"\x06device\x18\x06 \x01(\v2\x14.bobobeads.v1.DeviceR\x06device\x12)\n" +
	"\x10guest_credential\x18\a \x01(\tR\x0fguestCredential\"Y\n" +
	"\x0eResponseHeader\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\">\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"p\n" +
	"\fPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore*\x84\x01\n" +
	"\bLanguage\x12\v\n" +
	"\aCHINESE\x10\x00\x12\v\n" +
	"\aENGLISH\x10\x01\x12\v\n" +
	"\aRUSSIAN\x10\x02\x12\x0e\n" +
	"\n" +
	"VIETNAMESE\x10\x03\x12\x0e\n" +
	"\n" +
	"PORTUGUESE\x10\x04\x12\x0e\n" +
	"\n" +
	"INDONESIAN\x10\x05\x12\t\n" +
	"\x05MALAY\x10\x06\x12\b\n" +
	"\x04THAI\x10\a\x12\f\n" +
	"\bFILIPINO\x10\b*t\n" +
	"\bPlatform\x12\x14\n" +
	"\x10PLATFORM_UNKNOWN\x10\x00\x12\x10\n" +
	"\fPLATFORM_IOS\x10\x01\x12\x14\n" +
	"\x10PLATFORM_ANDROID\x10\x02\x12\x18\n" +
	"\x14PLATFORM_MINIPROGRAM\x10\x03\x12\x10\n" +
	"\fPLATFORM_WEB\x10\x04B\xa3\x01\n" +
	"\x10com.bobobeads.v1B\vCommonProtoP\x01Z1github.com/zhaojiabo/bobobeads_server/internal/pb\xa2\x02\x03BXX\xaa\x02\fBobobeads.V1\xca\x02\fBobobeads\\V1\xe2\x02\x18Bobobeads\\V1\\GPBMetadata\xea\x02\rBobobeads::V1b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_proto_goTypes = []any{
	(Language)(0),           // 0: bobobeads.v1.Language
	(Platform)(0),           // 1: bobobeads.v1.Platform
	(*Device)(nil),          // 2: bobobeads.v1.Device
	(*RequestHeader)(nil),   // 3: bobobeads.v1.RequestHeader
	(*ResponseHeader)(nil),  // 4: bobobeads.v1.ResponseHeader
	(*PageRequest)(nil),     // 5: bobobeads.v1.PageRequest
	(*PageResponse)(nil),    // 6: bobobeads.v1.PageResponse
	(*Device_Geo)(nil),      // 7: bobobeads.v1.Device.Geo
	(*Device_CAID)(nil),     // 8: bobobeads.v1.Device.CAID
	(*Device_UserInfo)(nil), // 9: bobobeads.v1.Device.UserInfo
}
var file_common_proto_depIdxs = []int32{
	7, // 0: bobobeads.v1.Device.geo:type_name -> bobobeads.v1.Device.Geo
	8, // 1: bobobeads.v1.Device.caids:type_name -> bobobeads.v1.Device.CAID
	9, // 2: bobobeads.v1.Device.user_info:type_name -> bobobeads.v1.Device.UserInfo
	0, // 3: bobobeads.v1.Device.language:type_name -> bobobeads.v1.Language
	2, // 4: bobobeads.v1.RequestHeader.device:type_name -> bobobeads.v1.Device
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
