// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: generation.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGenerationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 豆板规格。
	BoardSpec string `protobuf:"bytes,2,opt,name=board_spec,json=boardSpec,proto3" json:"board_spec,omitempty"`
	// 生成来源类型：photo、album、template。
	SourceType string `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// 来源 ID，模板来源时为 template_id。
	SourceId string `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// 客户端请求幂等 ID。
	ClientRequestId string `protobuf:"bytes,5,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGenerationRequest) Reset() {
	*x = CreateGenerationRequest{}
	mi := &file_generation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenerationRequest) ProtoMessage() {}

func (x *CreateGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenerationRequest.ProtoReflect.Descriptor instead.
func (*CreateGenerationRequest) Descriptor() ([]byte, []int) {
	return file_generation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGenerationRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateGenerationRequest) GetBoardSpec() string {
	if x != nil {
		return x.BoardSpec
	}
	return ""
}

func (x *CreateGenerationRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CreateGenerationRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CreateGenerationRequest) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

type CreateGenerationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 生成记录 ID。
	GenerationId string `protobuf:"bytes,2,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	// 本次扣除积分。
	CreditsDeducted int32 `protobuf:"varint,3,opt,name=credits_deducted,json=creditsDeducted,proto3" json:"credits_deducted,omitempty"`
	// 剩余积分余额。
	RemainingBalance int32 `protobuf:"varint,4,opt,name=remaining_balance,json=remainingBalance,proto3" json:"remaining_balance,omitempty"`
	// 生成记录过期时间戳。
	ExpiresAt int64 `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// 是否命中重复请求。
	Duplicated    bool `protobuf:"varint,6,opt,name=duplicated,proto3" json:"duplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGenerationResponse) Reset() {
	*x = CreateGenerationResponse{}
	mi := &file_generation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenerationResponse) ProtoMessage() {}

func (x *CreateGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenerationResponse.ProtoReflect.Descriptor instead.
func (*CreateGenerationResponse) Descriptor() ([]byte, []int) {
	return file_generation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGenerationResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateGenerationResponse) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

func (x *CreateGenerationResponse) GetCreditsDeducted() int32 {
	if x != nil {
		return x.CreditsDeducted
	}
	return 0
}

func (x *CreateGenerationResponse) GetRemainingBalance() int32 {
	if x != nil {
		return x.RemainingBalance
	}
	return 0
}

func (x *CreateGenerationResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CreateGenerationResponse) GetDuplicated() bool {
	if x != nil {
		return x.Duplicated
	}
	return false
}

type CompleteGenerationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 生成记录 ID。
	GenerationId string `protobuf:"bytes,2,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	// 作品标题。
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// 原图地址。
	OriginalImageUrl string `protobuf:"bytes,4,opt,name=original_image_url,json=originalImageUrl,proto3" json:"original_image_url,omitempty"`
	// 图纸图片地址。
	PatternImageUrl string `protobuf:"bytes,5,opt,name=pattern_image_url,json=patternImageUrl,proto3" json:"pattern_image_url,omitempty"`
	// 图纸数据。
	PatternData *PatternData `protobuf:"bytes,6,opt,name=pattern_data,json=patternData,proto3" json:"pattern_data,omitempty"`
	// 客户端展示用统计值；服务端会按 pattern_data 的非零 pixels 重算并忽略该值。
	BeadCount int32 `protobuf:"varint,7,opt,name=bead_count,json=beadCount,proto3" json:"bead_count,omitempty"`
	// 客户端展示用统计值；服务端会按 pattern_data 的实际使用颜色重算并忽略该值。
	ColorCount    int32 `protobuf:"varint,8,opt,name=color_count,json=colorCount,proto3" json:"color_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteGenerationRequest) Reset() {
	*x = CompleteGenerationRequest{}
	mi := &file_generation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteGenerationRequest) ProtoMessage() {}

func (x *CompleteGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteGenerationRequest.ProtoReflect.Descriptor instead.
func (*CompleteGenerationRequest) Descriptor() ([]byte, []int) {
	return file_generation_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteGenerationRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CompleteGenerationRequest) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

func (x *CompleteGenerationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CompleteGenerationRequest) GetOriginalImageUrl() string {
	if x != nil {
		return x.OriginalImageUrl
	}
	return ""
}

func (x *CompleteGenerationRequest) GetPatternImageUrl() string {
	if x != nil {
		return x.PatternImageUrl
	}
	return ""
}

func (x *CompleteGenerationRequest) GetPatternData() *PatternData {
	if x != nil {
		return x.PatternData
	}
	return nil
}

func (x *CompleteGenerationRequest) GetBeadCount() int32 {
	if x != nil {
		return x.BeadCount
	}
	return 0
}

func (x *CompleteGenerationRequest) GetColorCount() int32 {
	if x != nil {
		return x.ColorCount
	}
	return 0
}

type CompleteGenerationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 生成后的作品 ID。
	WorkId string `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	// 是否命中重复请求。
	Duplicated    bool `protobuf:"varint,3,opt,name=duplicated,proto3" json:"duplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteGenerationResponse) Reset() {
	*x = CompleteGenerationResponse{}
	mi := &file_generation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteGenerationResponse) ProtoMessage() {}

func (x *CompleteGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteGenerationResponse.ProtoReflect.Descriptor instead.
func (*CompleteGenerationResponse) Descriptor() ([]byte, []int) {
	return file_generation_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteGenerationResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CompleteGenerationResponse) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *CompleteGenerationResponse) GetDuplicated() bool {
	if x != nil {
		return x.Duplicated
	}
	return false
}

type CancelGenerationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 生成记录 ID。
	GenerationId string `protobuf:"bytes,2,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	// 取消原因。
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelGenerationRequest) Reset() {
	*x = CancelGenerationRequest{}
	mi := &file_generation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelGenerationRequest) ProtoMessage() {}

func (x *CancelGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelGenerationRequest.ProtoReflect.Descriptor instead.
func (*CancelGenerationRequest) Descriptor() ([]byte, []int) {
	return file_generation_proto_rawDescGZIP(), []int{4}
}

func (x *CancelGenerationRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CancelGenerationRequest) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

func (x *CancelGenerationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelGenerationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 退回积分数量。
	CreditsRefunded int32 `protobuf:"varint,2,opt,name=credits_refunded,json=creditsRefunded,proto3" json:"credits_refunded,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelGenerationResponse) Reset() {
	*x = CancelGenerationResponse{}
	mi := &file_generation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelGenerationResponse) ProtoMessage() {}

func (x *CancelGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelGenerationResponse.ProtoReflect.Descriptor instead.
func (*CancelGenerationResponse) Descriptor() ([]byte, []int) {
	return file_generation_proto_rawDescGZIP(), []int{5}
}

func (x *CancelGenerationResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CancelGenerationResponse) GetCreditsRefunded() int32 {
	if x != nil {
		return x.CreditsRefunded
	}
	return 0
}

type GetGenerationStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 生成记录 ID。
	GenerationId  string `protobuf:"bytes,2,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenerationStatusRequest) Reset() {
	*x = GetGenerationStatusRequest{}
	mi := &file_generation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationStatusRequest) ProtoMessage() {}

func (x *GetGenerationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetGenerationStatusRequest) Descriptor() ([]byte, []int) {
	return file_generation_proto_rawDescGZIP(), []int{6}
}

func (x *GetGenerationStatusRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetGenerationStatusRequest) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

type GetGenerationStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 生成状态：0 待完成，1 已完成，2 已取消，3 已过期。
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	// 已扣除积分。
	CreditsDeducted int32 `protobuf:"varint,3,opt,name=credits_deducted,json=creditsDeducted,proto3" json:"credits_deducted,omitempty"`
	// 关联作品 ID。
	WorkId        string `protobuf:"bytes,4,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenerationStatusResponse) Reset() {
	*x = GetGenerationStatusResponse{}
	mi := &file_generation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationStatusResponse) ProtoMessage() {}

func (x *GetGenerationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetGenerationStatusResponse) Descriptor() ([]byte, []int) {
	return file_generation_proto_rawDescGZIP(), []int{7}
}

func (x *GetGenerationStatusResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetGenerationStatusResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetCreditsDeducted() int32 {
	if x != nil {
		return x.CreditsDeducted
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

var File_generation_proto protoreflect.FileDescriptor

const file_generation_proto_rawDesc = "" +
	"\n" +
	"\x10generation.proto\x12\fbobobeads.v1\x1a\fcommon.proto\x1a\n" +
	"work.proto\x1a\x1cgoogle/api/annotations.proto\"\xd7\x01\n" +
	"\x17CreateGenerationRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x1d\n" +
	"\n" +
	"board_spec\x18\x02 \x01(\tR\tboardSpec\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12*\n" +
	"\x11client_request_id\x18\x05 \x01(\tR\x0fclientRequestId\"\x8c\x02\n" +
	"\x18CreateGenerationResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12#\n" +
	"\rgeneration_id\x18\x02 \x01(\tR\fgenerationId\x12)\n" +
	"\x10credits_deducted\x18\x03 \x01(\x05R\x0fcreditsDeducted\x12+\n" +
	"\x11remaining_balance\x18\x04 \x01(\x05R\x10remainingBalance\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12\x1e\n" +
	"\n" +
	"duplicated\x18\x06 \x01(\bR\n" +
	"duplicated\"\xe3\x02\n" +
	"\x19CompleteGenerationRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12#\n" +
	"\rgeneration_id\x18\x02 \x01(\tR\fgenerationId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12,\n" +
	"\x12original_image_url\x18\x04 \x01(\tR\x10originalImageUrl\x12*\n" +
	"\x11pattern_image_url\x18\x05 \x01(\tR\x0fpatternImageUrl\x12<\n" +
	"\fpattern_data\x18\x06 \x01(\v2\x19.bobobeads.v1.PatternDataR\vpatternData\x12\x1d\n" +
	"\n" +
	"bead_count\x18\a \x01(\x05R\tbeadCount\x12\x1f\n" +
	"\vcolor_count\x18\b \x01(\x05R\n" +
	"colorCount\"\x8b\x01\n" +
	"\x1aCompleteGenerationResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\x12\x1e\n" +
	"\n" +
	"duplicated\x18\x03 \x01(\bR\n" +
	"duplicated\"\x8b\x01\n" +
	"\x17CancelGenerationRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12#\n" +
	"\rgeneration_id\x18\x02 \x01(\tR\fgenerationId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"{\n" +
	"\x18CancelGenerationResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12)\n" +
	"\x10credits_refunded\x18\x02 \x01(\x05R\x0fcreditsRefunded\"v\n" +
	"\x1aGetGenerationStatusRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12#\n" +
	"\rgeneration_id\x18\x02 \x01(\tR\fgenerationId\"\xaf\x01\n" +
	"\x1bGetGenerationStatusResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12)\n" +
	"\x10credits_deducted\x18\x03 \x01(\x05R\x0fcreditsDeducted\x12\x17\n" +
	"\awork_id\x18\x04 \x01(\tR\x06workId2\xf2\x04\n" +
	"\x11GenerationService\x12\x87\x01\n" +
	"\x10CreateGeneration\x12%.bobobeads.v1.CreateGenerationRequest\x1a&.bobobeads.v1.CreateGenerationResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/generation/create\x12\x9f\x01\n" +
	"\x12CompleteGeneration\x12'.bobobeads.v1.CompleteGenerationRequest\x1a(.bobobeads.v1.CompleteGenerationResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/api/v1/generation/{generation_id}/complete\x12\x97\x01\n" +
	"\x10CancelGeneration\x12%.bobobeads.v1.CancelGenerationRequest\x1a&.bobobeads.v1.CancelGenerationResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/v1/generation/{generation_id}/cancel\x12\x96\x01\n" +
	"\x13GetGenerationStatus\x12(.bobobeads.v1.GetGenerationStatusRequest\x1a).bobobeads.v1.GetGenerationStatusResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/generation/{generation_id}B\xa7\x01\n" +
	"\x10com.bobobeads.v1B\x0fGenerationProtoP\x01Z1github.com/zhaojiabo/bobobeads_server/internal/pb\xa2\x02\x03BXX\xaa\x02\fBobobeads.V1\xca\x02\fBobobeads\\V1\xe2\x02\x18Bobobeads\\V1\\GPBMetadata\xea\x02\rBobobeads::V1b\x06proto3"

var (
	file_generation_proto_rawDescOnce sync.Once
	file_generation_proto_rawDescData []byte
)

func file_generation_proto_rawDescGZIP() []byte {
	file_generation_proto_rawDescOnce.Do(func() {
		file_generation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generation_proto_rawDesc), len(file_generation_proto_rawDesc)))
	})
	return file_generation_proto_rawDescData
}

var file_generation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_generation_proto_goTypes = []any{
	(*CreateGenerationRequest)(nil),     // 0: bobobeads.v1.CreateGenerationRequest
	(*CreateGenerationResponse)(nil),    // 1: bobobeads.v1.CreateGenerationResponse
	(*CompleteGenerationRequest)(nil),   // 2: bobobeads.v1.CompleteGenerationRequest
	(*CompleteGenerationResponse)(nil),  // 3: bobobeads.v1.CompleteGenerationResponse
	(*CancelGenerationRequest)(nil),     // 4: bobobeads.v1.CancelGenerationRequest
	(*CancelGenerationResponse)(nil),    // 5: bobobeads.v1.CancelGenerationResponse
	(*GetGenerationStatusRequest)(nil),  // 6: bobobeads.v1.GetGenerationStatusRequest
	(*GetGenerationStatusResponse)(nil), // 7: bobobeads.v1.GetGenerationStatusResponse
	(*RequestHeader)(nil),               // 8: bobobeads.v1.RequestHeader
	(*ResponseHeader)(nil),              // 9: bobobeads.v1.ResponseHeader
	(*PatternData)(nil),                 // 10: bobobeads.v1.PatternData
}
var file_generation_proto_depIdxs = []int32{
	8,  // 0: bobobeads.v1.CreateGenerationRequest.header:type_name -> bobobeads.v1.RequestHeader
	9,  // 1: bobobeads.v1.CreateGenerationResponse.header:type_name -> bobobeads.v1.ResponseHeader
	8,  // 2: bobobeads.v1.CompleteGenerationRequest.header:type_name -> bobobeads.v1.RequestHeader
	10, // 3: bobobeads.v1.CompleteGenerationRequest.pattern_data:type_name -> bobobeads.v1.PatternData
	9,  // 4: bobobeads.v1.CompleteGenerationResponse.header:type_name -> bobobeads.v1.ResponseHeader
	8,  // 5: bobobeads.v1.CancelGenerationRequest.header:type_name -> bobobeads.v1.RequestHeader
	9,  // 6: bobobeads.v1.CancelGenerationResponse.header:type_name -> bobobeads.v1.ResponseHeader
	8,  // 7: bobobeads.v1.GetGenerationStatusRequest.header:type_name -> bobobeads.v1.RequestHeader
	9,  // 8: bobobeads.v1.GetGenerationStatusResponse.header:type_name -> bobobeads.v1.ResponseHeader
	0,  // 9: bobobeads.v1.GenerationService.CreateGeneration:input_type -> bobobeads.v1.CreateGenerationRequest
	2,  // 10: bobobeads.v1.GenerationService.CompleteGeneration:input_type -> bobobeads.v1.CompleteGenerationRequest
	4,  // 11: bobobeads.v1.GenerationService.CancelGeneration:input_type -> bobobeads.v1.CancelGenerationRequest
	6,  // 12: bobobeads.v1.GenerationService.GetGenerationStatus:input_type -> bobobeads.v1.GetGenerationStatusRequest
	1,  // 13: bobobeads.v1.GenerationService.CreateGeneration:output_type -> bobobeads.v1.CreateGenerationResponse
	3,  // 14: bobobeads.v1.GenerationService.CompleteGeneration:output_type -> bobobeads.v1.CompleteGenerationResponse
	5,  // 15: bobobeads.v1.GenerationService.CancelGeneration:output_type -> bobobeads.v1.CancelGenerationResponse
	7,  // 16: bobobeads.v1.GenerationService.GetGenerationStatus:output_type -> bobobeads.v1.GetGenerationStatusResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_generation_proto_init() }
func file_generation_proto_init() {
	if File_generation_proto != nil {
		return
	}
	file_common_proto_init()
	file_work_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generation_proto_rawDesc), len(file_generation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generation_proto_goTypes,
		DependencyIndexes: file_generation_proto_depIdxs,
		MessageInfos:      file_generation_proto_msgTypes,
	}.Build()
	File_generation_proto = out.File
	file_generation_proto_goTypes = nil
	file_generation_proto_depIdxs = nil
}
