// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: report.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 事件名称。
	EventName string `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// 事件参数。
	Params map[string]string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 事件发生时间戳。
	Timestamp     int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventItem) Reset() {
	*x = EventItem{}
	mi := &file_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventItem) ProtoMessage() {}

func (x *EventItem) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventItem.ProtoReflect.Descriptor instead.
func (*EventItem) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

func (x *EventItem) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EventItem) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *EventItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReportEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 事件列表。
	Events        []*EventItem `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEventRequest) Reset() {
	*x = ReportEventRequest{}
	mi := &file_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventRequest) ProtoMessage() {}

func (x *ReportEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventRequest.ProtoReflect.Descriptor instead.
func (*ReportEventRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{1}
}

func (x *ReportEventRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReportEventRequest) GetEvents() []*EventItem {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReportEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header        *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEventResponse) Reset() {
	*x = ReportEventResponse{}
	mi := &file_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventResponse) ProtoMessage() {}

func (x *ReportEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventResponse.ProtoReflect.Descriptor instead.
func (*ReportEventResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{2}
}

func (x *ReportEventResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type ReportErrorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 错误类型。
	ErrorType string `protobuf:"bytes,2,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	// 错误消息。
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// 错误堆栈。
	StackTrace string `protobuf:"bytes,4,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	// 错误上下文。
	Context       map[string]string `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportErrorRequest) Reset() {
	*x = ReportErrorRequest{}
	mi := &file_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportErrorRequest) ProtoMessage() {}

func (x *ReportErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportErrorRequest.ProtoReflect.Descriptor instead.
func (*ReportErrorRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{3}
}

func (x *ReportErrorRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReportErrorRequest) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *ReportErrorRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportErrorRequest) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *ReportErrorRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type ReportErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header        *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportErrorResponse) Reset() {
	*x = ReportErrorResponse{}
	mi := &file_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportErrorResponse) ProtoMessage() {}

func (x *ReportErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportErrorResponse.ProtoReflect.Descriptor instead.
func (*ReportErrorResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{4}
}

func (x *ReportErrorResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type SubmitFeedbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 反馈内容。
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// 联系方式。
	Contact string `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	// 附图地址列表。
	ImageUrls     []string `protobuf:"bytes,4,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFeedbackRequest) Reset() {
	*x = SubmitFeedbackRequest{}
	mi := &file_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackRequest) ProtoMessage() {}

func (x *SubmitFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackRequest.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitFeedbackRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SubmitFeedbackRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SubmitFeedbackRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *SubmitFeedbackRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type SubmitFeedbackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header        *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFeedbackResponse) Reset() {
	*x = SubmitFeedbackResponse{}
	mi := &file_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackResponse) ProtoMessage() {}

func (x *SubmitFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackResponse.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitFeedbackResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_report_proto protoreflect.FileDescriptor

const file_report_proto_rawDesc = "" +
	"\n" +
	"\freport.proto\x12\fbobobeads.v1\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\"\xc0\x01\n" +
	"\tEventItem\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12;\n" +
	"\x06params\x18\x02 \x03(\v2#.bobobeads.v1.EventItem.ParamsEntryR\x06params\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x12ReportEventRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12/\n" +
	"\x06events\x18\x02 \x03(\v2\x17.bobobeads.v1.EventItemR\x06events\"K\n" +
	"\x13ReportEventResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\"\xa8\x02\n" +
	"\x12ReportErrorRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x1d\n" +
	"\n" +
	"error_type\x18\x02 \x01(\tR\terrorType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vstack_trace\x18\x04 \x01(\tR\n" +
	"stackTrace\x12G\n" +
	"\acontext\x18\x05 \x03(\v2-.bobobeads.v1.ReportErrorRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x13ReportErrorResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\"\x9f\x01\n" +
	"\x15SubmitFeedbackRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\acontact\x18\x03 \x01(\tR\acontact\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x04 \x03(\tR\timageUrls\"N\n" +
	"\x16SubmitFeedbackResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header2\xfa\x02\n" +
	"\rReportService\x12s\n" +
	"\vReportEvent\x12 .bobobeads.v1.ReportEventRequest\x1a!.bobobeads.v1.ReportEventResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/report/event\x12s\n" +
	"\vReportError\x12 .bobobeads.v1.ReportErrorRequest\x1a!.bobobeads.v1.ReportErrorResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/report/error\x12\x7f\n" +
	"\x0eSubmitFeedback\x12#.bobobeads.v1.SubmitFeedbackRequest\x1a$.bobobeads.v1.SubmitFeedbackResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/report/feedbackB\xa3\x01\n" +
	"\x10com.bobobeads.v1B\vReportProtoP\x01Z1github.com/zhaojiabo/bobobeads_server/internal/pb\xa2\x02\x03BXX\xaa\x02\fBobobeads.V1\xca\x02\fBobobeads\\V1\xe2\x02\x18Bobobeads\\V1\\GPBMetadata\xea\x02\rBobobeads::V1b\x06proto3"

var (
	file_report_proto_rawDescOnce sync.Once
	file_report_proto_rawDescData []byte
)

func file_report_proto_rawDescGZIP() []byte {
	file_report_proto_rawDescOnce.Do(func() {
		file_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)))
	})
	return file_report_proto_rawDescData
}

var file_report_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_report_proto_goTypes = []any{
	(*EventItem)(nil),              // 0: bobobeads.v1.EventItem
	(*ReportEventRequest)(nil),     // 1: bobobeads.v1.ReportEventRequest
	(*ReportEventResponse)(nil),    // 2: bobobeads.v1.ReportEventResponse
	(*ReportErrorRequest)(nil),     // 3: bobobeads.v1.ReportErrorRequest
	(*ReportErrorResponse)(nil),    // 4: bobobeads.v1.ReportErrorResponse
	(*SubmitFeedbackRequest)(nil),  // 5: bobobeads.v1.SubmitFeedbackRequest
	(*SubmitFeedbackResponse)(nil), // 6: bobobeads.v1.SubmitFeedbackResponse
	nil,                            // 7: bobobeads.v1.EventItem.ParamsEntry
	nil,                            // 8: bobobeads.v1.ReportErrorRequest.ContextEntry
	(*RequestHeader)(nil),          // 9: bobobeads.v1.RequestHeader
	(*ResponseHeader)(nil),         // 10: bobobeads.v1.ResponseHeader
}
var file_report_proto_depIdxs = []int32{
	7,  // 0: bobobeads.v1.EventItem.params:type_name -> bobobeads.v1.EventItem.ParamsEntry
	9,  // 1: bobobeads.v1.ReportEventRequest.header:type_name -> bobobeads.v1.RequestHeader
	0,  // 2: bobobeads.v1.ReportEventRequest.events:type_name -> bobobeads.v1.EventItem
	10, // 3: bobobeads.v1.ReportEventResponse.header:type_name -> bobobeads.v1.ResponseHeader
	9,  // 4: bobobeads.v1.ReportErrorRequest.header:type_name -> bobobeads.v1.RequestHeader
	8,  // 5: bobobeads.v1.ReportErrorRequest.context:type_name -> bobobeads.v1.ReportErrorRequest.ContextEntry
	10, // 6: bobobeads.v1.ReportErrorResponse.header:type_name -> bobobeads.v1.ResponseHeader
	9,  // 7: bobobeads.v1.SubmitFeedbackRequest.header:type_name -> bobobeads.v1.RequestHeader
	10, // 8: bobobeads.v1.SubmitFeedbackResponse.header:type_name -> bobobeads.v1.ResponseHeader
	1,  // 9: bobobeads.v1.ReportService.ReportEvent:input_type -> bobobeads.v1.ReportEventRequest
	3,  // 10: bobobeads.v1.ReportService.ReportError:input_type -> bobobeads.v1.ReportErrorRequest
	5,  // 11: bobobeads.v1.ReportService.SubmitFeedback:input_type -> bobobeads.v1.SubmitFeedbackRequest
	2,  // 12: bobobeads.v1.ReportService.ReportEvent:output_type -> bobobeads.v1.ReportEventResponse
	4,  // 13: bobobeads.v1.ReportService.ReportError:output_type -> bobobeads.v1.ReportErrorResponse
	6,  // 14: bobobeads.v1.ReportService.SubmitFeedback:output_type -> bobobeads.v1.SubmitFeedbackResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_report_proto_init() }
func file_report_proto_init() {
	if File_report_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_proto_goTypes,
		DependencyIndexes: file_report_proto_depIdxs,
		MessageInfos:      file_report_proto_msgTypes,
	}.Build()
	File_report_proto = out.File
	file_report_proto_goTypes = nil
	file_report_proto_depIdxs = nil
}
