// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: subscribe.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品 ID。
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// 商品 SKU。
	Sku string `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	// 商品名称。
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 商品描述。
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// 价格，单位分。
	PriceCents int32 `protobuf:"varint,5,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	// 币种。
	Currency string `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	// 有效天数。
	DurationDays int32 `protobuf:"varint,7,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	// Apple 内购商品 ID。
	AppleProductId string `protobuf:"bytes,8,opt,name=apple_product_id,json=appleProductId,proto3" json:"apple_product_id,omitempty"`
	// 商品权益列表。
	Features      []string `protobuf:"bytes,9,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductItem) Reset() {
	*x = ProductItem{}
	mi := &file_subscribe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductItem) ProtoMessage() {}

func (x *ProductItem) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductItem.ProtoReflect.Descriptor instead.
func (*ProductItem) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{0}
}

func (x *ProductItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductItem) GetPriceCents() int32 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *ProductItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProductItem) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *ProductItem) GetAppleProductId() string {
	if x != nil {
		return x.AppleProductId
	}
	return ""
}

func (x *ProductItem) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type OrderItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 订单号。
	OrderNo string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	// 商品名称。
	ProductName string `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	// 支付金额，单位分。
	AmountCents int32 `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	// 币种。
	Currency string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	// 支付方式。
	PaymentMethod string `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	// 订单状态。
	Status int32 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	// 创建时间戳。
	CreatedAt int64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 支付时间戳。
	PaidAt        int64 `protobuf:"varint,8,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_subscribe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetAmountCents() int32 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *OrderItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *OrderItem) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OrderItem) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

type ListProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header        *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_subscribe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductsRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type ListProductsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 商品列表。
	Products      []*ProductItem `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_subscribe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListProductsResponse) GetProducts() []*ProductItem {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 商品 ID。
	ProductId string `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// 支付方式。
	PaymentMethod string `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_subscribe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateOrderRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrderRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type CreateOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 订单号。
	OrderNo       string `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_subscribe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateOrderResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetPaymentParamsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 订单号。
	OrderNo       string `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentParamsRequest) Reset() {
	*x = GetPaymentParamsRequest{}
	mi := &file_subscribe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentParamsRequest) ProtoMessage() {}

func (x *GetPaymentParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentParamsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentParamsRequest) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentParamsRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetPaymentParamsRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetPaymentParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 支付方式。
	PaymentMethod string `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	// 支付参数。
	Params        map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentParamsResponse) Reset() {
	*x = GetPaymentParamsResponse{}
	mi := &file_subscribe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentParamsResponse) ProtoMessage() {}

func (x *GetPaymentParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentParamsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentParamsResponse) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaymentParamsResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetPaymentParamsResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *GetPaymentParamsResponse) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type PaymentCallbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 支付方式。
	PaymentMethod string `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	// 支付回调原始数据。
	RawData       string `protobuf:"bytes,3,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackRequest) Reset() {
	*x = PaymentCallbackRequest{}
	mi := &file_subscribe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackRequest) ProtoMessage() {}

func (x *PaymentCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackRequest.ProtoReflect.Descriptor instead.
func (*PaymentCallbackRequest) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentCallbackRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PaymentCallbackRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PaymentCallbackRequest) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

type PaymentCallbackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 是否处理成功。
	Success       bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackResponse) Reset() {
	*x = PaymentCallbackResponse{}
	mi := &file_subscribe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackResponse) ProtoMessage() {}

func (x *PaymentCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackResponse.ProtoReflect.Descriptor instead.
func (*PaymentCallbackResponse) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentCallbackResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PaymentCallbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RestorePurchaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 购买凭证数据。
	ReceiptData   string `protobuf:"bytes,2,opt,name=receipt_data,json=receiptData,proto3" json:"receipt_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestorePurchaseRequest) Reset() {
	*x = RestorePurchaseRequest{}
	mi := &file_subscribe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestorePurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestorePurchaseRequest) ProtoMessage() {}

func (x *RestorePurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestorePurchaseRequest.ProtoReflect.Descriptor instead.
func (*RestorePurchaseRequest) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{10}
}

func (x *RestorePurchaseRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RestorePurchaseRequest) GetReceiptData() string {
	if x != nil {
		return x.ReceiptData
	}
	return ""
}

type RestorePurchaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 是否为会员。
	IsVip bool `protobuf:"varint,2,opt,name=is_vip,json=isVip,proto3" json:"is_vip,omitempty"`
	// 会员过期时间戳。
	ExpireAt      int64 `protobuf:"varint,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestorePurchaseResponse) Reset() {
	*x = RestorePurchaseResponse{}
	mi := &file_subscribe_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestorePurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestorePurchaseResponse) ProtoMessage() {}

func (x *RestorePurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestorePurchaseResponse.ProtoReflect.Descriptor instead.
func (*RestorePurchaseResponse) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{11}
}

func (x *RestorePurchaseResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RestorePurchaseResponse) GetIsVip() bool {
	if x != nil {
		return x.IsVip
	}
	return false
}

func (x *RestorePurchaseResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type GetSubscriptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header        *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_subscribe_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{12}
}

func (x *GetSubscriptionRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type GetSubscriptionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 是否为会员。
	IsVip bool `protobuf:"varint,2,opt,name=is_vip,json=isVip,proto3" json:"is_vip,omitempty"`
	// 订阅计划名称。
	PlanName string `protobuf:"bytes,3,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	// 会员过期时间戳。
	ExpireAt int64 `protobuf:"varint,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// 是否自动续费。
	AutoRenew     bool `protobuf:"varint,5,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_subscribe_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{13}
}

func (x *GetSubscriptionResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetSubscriptionResponse) GetIsVip() bool {
	if x != nil {
		return x.IsVip
	}
	return false
}

func (x *GetSubscriptionResponse) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *GetSubscriptionResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *GetSubscriptionResponse) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

type ListOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 分页参数。
	Page          *PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_subscribe_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{14}
}

func (x *ListOrdersRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListOrdersRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListOrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 订单列表。
	Orders []*OrderItem `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	// 分页信息。
	Page          *PageResponse `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_subscribe_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribe_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_subscribe_proto_rawDescGZIP(), []int{15}
}

func (x *ListOrdersResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListOrdersResponse) GetOrders() []*OrderItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_subscribe_proto protoreflect.FileDescriptor

const file_subscribe_proto_rawDesc = "" +
	"\n" +
	"\x0fsubscribe.proto\x12\fbobobeads.v1\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\"\x9c\x02\n" +
	"\vProductItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_cents\x18\x05 \x01(\x05R\n" +
	"priceCents\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12#\n" +
	"\rduration_days\x18\a \x01(\x05R\fdurationDays\x12(\n" +
	"\x10apple_product_id\x18\b \x01(\tR\x0eappleProductId\x12\x1a\n" +
	"\bfeatures\x18\t \x03(\tR\bfeatures\"\xff\x01\n" +
	"\tOrderItem\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x05R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x17\n" +
	"\apaid_at\x18\b \x01(\x03R\x06paidAt\"J\n" +
	"\x13ListProductsRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"\x83\x01\n" +
	"\x14ListProductsResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x125\n" +
	"\bproducts\x18\x02 \x03(\v2\x19.bobobeads.v1.ProductItemR\bproducts\"\x8f\x01\n" +
	"\x12CreateOrderRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\"f\n" +
	"\x13CreateOrderResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"i\n" +
	"\x17GetPaymentParamsRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"\xfe\x01\n" +
	"\x18GetPaymentParamsResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12J\n" +
	"\x06params\x18\x03 \x03(\v22.bobobeads.v1.GetPaymentParamsResponse.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x16PaymentCallbackRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12\x19\n" +
	"\braw_data\x18\x03 \x01(\tR\arawData\"i\n" +
	"\x17PaymentCallbackResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"p\n" +
	"\x16RestorePurchaseRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12!\n" +
	"\freceipt_data\x18\x02 \x01(\tR\vreceiptData\"\x83\x01\n" +
	"\x17RestorePurchaseResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12\x15\n" +
	"\x06is_vip\x18\x02 \x01(\bR\x05isVip\x12\x1b\n" +
	"\texpire_at\x18\x03 \x01(\x03R\bexpireAt\"M\n" +
	"\x16GetSubscriptionRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"\xbf\x01\n" +
	"\x17GetSubscriptionResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12\x15\n" +
	"\x06is_vip\x18\x02 \x01(\bR\x05isVip\x12\x1b\n" +
	"\tplan_name\x18\x03 \x01(\tR\bplanName\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\x03R\bexpireAt\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\x05 \x01(\bR\tautoRenew\"w\n" +
	"\x11ListOrdersRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12-\n" +
	"\x04page\x18\x02 \x01(\v2\x19.bobobeads.v1.PageRequestR\x04page\"\xab\x01\n" +
	"\x12ListOrdersResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12/\n" +
	"\x06orders\x18\x02 \x03(\v2\x17.bobobeads.v1.OrderItemR\x06orders\x12.\n" +
	"\x04page\x18\x03 \x01(\v2\x1a.bobobeads.v1.PageResponseR\x04page2\xa4\a\n" +
	"\x10SubscribeService\x12y\n" +
	"\fListProducts\x12!.bobobeads.v1.ListProductsRequest\x1a\".bobobeads.v1.ListProductsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/subscribe/products\x12w\n" +
	"\vCreateOrder\x12 .bobobeads.v1.CreateOrderRequest\x1a!.bobobeads.v1.CreateOrderResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/subscribe/orders\x12\x96\x01\n" +
	"\x10GetPaymentParams\x12%.bobobeads.v1.GetPaymentParamsRequest\x1a&.bobobeads.v1.GetPaymentParamsResponse\"3\x82\xd3\xe4\x93\x02-\x12+/api/v1/subscribe/orders/{order_no}/payment\x12\x85\x01\n" +
	"\x0fPaymentCallback\x12$.bobobeads.v1.PaymentCallbackRequest\x1a%.bobobeads.v1.PaymentCallbackResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/subscribe/callback\x12\x84\x01\n" +
	"\x0fRestorePurchase\x12$.bobobeads.v1.RestorePurchaseRequest\x1a%.bobobeads.v1.RestorePurchaseResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/subscribe/restore\x12\x80\x01\n" +
	"\x0fGetSubscription\x12$.bobobeads.v1.GetSubscriptionRequest\x1a%.bobobeads.v1.GetSubscriptionResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/subscribe/status\x12q\n" +
	"\n" +
	"ListOrders\x12\x1f.bobobeads.v1.ListOrdersRequest\x1a .bobobeads.v1.ListOrdersResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/subscribe/ordersB\xa6\x01\n" +
	"\x10com.bobobeads.v1B\x0eSubscribeProtoP\x01Z1github.com/zhaojiabo/bobobeads_server/internal/pb\xa2\x02\x03BXX\xaa\x02\fBobobeads.V1\xca\x02\fBobobeads\\V1\xe2\x02\x18Bobobeads\\V1\\GPBMetadata\xea\x02\rBobobeads::V1b\x06proto3"

var (
	file_subscribe_proto_rawDescOnce sync.Once
	file_subscribe_proto_rawDescData []byte
)

func file_subscribe_proto_rawDescGZIP() []byte {
	file_subscribe_proto_rawDescOnce.Do(func() {
		file_subscribe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscribe_proto_rawDesc), len(file_subscribe_proto_rawDesc)))
	})
	return file_subscribe_proto_rawDescData
}

var file_subscribe_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_subscribe_proto_goTypes = []any{
	(*ProductItem)(nil),              // 0: bobobeads.v1.ProductItem
	(*OrderItem)(nil),                // 1: bobobeads.v1.OrderItem
	(*ListProductsRequest)(nil),      // 2: bobobeads.v1.ListProductsRequest
	(*ListProductsResponse)(nil),     // 3: bobobeads.v1.ListProductsResponse
	(*CreateOrderRequest)(nil),       // 4: bobobeads.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),      // 5: bobobeads.v1.CreateOrderResponse
	(*GetPaymentParamsRequest)(nil),  // 6: bobobeads.v1.GetPaymentParamsRequest
	(*GetPaymentParamsResponse)(nil), // 7: bobobeads.v1.GetPaymentParamsResponse
	(*PaymentCallbackRequest)(nil),   // 8: bobobeads.v1.PaymentCallbackRequest
	(*PaymentCallbackResponse)(nil),  // 9: bobobeads.v1.PaymentCallbackResponse
	(*RestorePurchaseRequest)(nil),   // 10: bobobeads.v1.RestorePurchaseRequest
	(*RestorePurchaseResponse)(nil),  // 11: bobobeads.v1.RestorePurchaseResponse
	(*GetSubscriptionRequest)(nil),   // 12: bobobeads.v1.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),  // 13: bobobeads.v1.GetSubscriptionResponse
	(*ListOrdersRequest)(nil),        // 14: bobobeads.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),       // 15: bobobeads.v1.ListOrdersResponse
	nil,                              // 16: bobobeads.v1.GetPaymentParamsResponse.ParamsEntry
	(*RequestHeader)(nil),            // 17: bobobeads.v1.RequestHeader
	(*ResponseHeader)(nil),           // 18: bobobeads.v1.ResponseHeader
	(*PageRequest)(nil),              // 19: bobobeads.v1.PageRequest
	(*PageResponse)(nil),             // 20: bobobeads.v1.PageResponse
}
var file_subscribe_proto_depIdxs = []int32{
	17, // 0: bobobeads.v1.ListProductsRequest.header:type_name -> bobobeads.v1.RequestHeader
	18, // 1: bobobeads.v1.ListProductsResponse.header:type_name -> bobobeads.v1.ResponseHeader
	0,  // 2: bobobeads.v1.ListProductsResponse.products:type_name -> bobobeads.v1.ProductItem
	17, // 3: bobobeads.v1.CreateOrderRequest.header:type_name -> bobobeads.v1.RequestHeader
	18, // 4: bobobeads.v1.CreateOrderResponse.header:type_name -> bobobeads.v1.ResponseHeader
	17, // 5: bobobeads.v1.GetPaymentParamsRequest.header:type_name -> bobobeads.v1.RequestHeader
	18, // 6: bobobeads.v1.GetPaymentParamsResponse.header:type_name -> bobobeads.v1.ResponseHeader
	16, // 7: bobobeads.v1.GetPaymentParamsResponse.params:type_name -> bobobeads.v1.GetPaymentParamsResponse.ParamsEntry
	17, // 8: bobobeads.v1.PaymentCallbackRequest.header:type_name -> bobobeads.v1.RequestHeader
	18, // 9: bobobeads.v1.PaymentCallbackResponse.header:type_name -> bobobeads.v1.ResponseHeader
	17, // 10: bobobeads.v1.RestorePurchaseRequest.header:type_name -> bobobeads.v1.RequestHeader
	18, // 11: bobobeads.v1.RestorePurchaseResponse.header:type_name -> bobobeads.v1.ResponseHeader
	17, // 12: bobobeads.v1.GetSubscriptionRequest.header:type_name -> bobobeads.v1.RequestHeader
	18, // 13: bobobeads.v1.GetSubscriptionResponse.header:type_name -> bobobeads.v1.ResponseHeader
	17, // 14: bobobeads.v1.ListOrdersRequest.header:type_name -> bobobeads.v1.RequestHeader
	19, // 15: bobobeads.v1.ListOrdersRequest.page:type_name -> bobobeads.v1.PageRequest
	18, // 16: bobobeads.v1.ListOrdersResponse.header:type_name -> bobobeads.v1.ResponseHeader
	1,  // 17: bobobeads.v1.ListOrdersResponse.orders:type_name -> bobobeads.v1.OrderItem
	20, // 18: bobobeads.v1.ListOrdersResponse.page:type_name -> bobobeads.v1.PageResponse
	2,  // 19: bobobeads.v1.SubscribeService.ListProducts:input_type -> bobobeads.v1.ListProductsRequest
	4,  // 20: bobobeads.v1.SubscribeService.CreateOrder:input_type -> bobobeads.v1.CreateOrderRequest
	6,  // 21: bobobeads.v1.SubscribeService.GetPaymentParams:input_type -> bobobeads.v1.GetPaymentParamsRequest
	8,  // 22: bobobeads.v1.SubscribeService.PaymentCallback:input_type -> bobobeads.v1.PaymentCallbackRequest
	10, // 23: bobobeads.v1.SubscribeService.RestorePurchase:input_type -> bobobeads.v1.RestorePurchaseRequest
	12, // 24: bobobeads.v1.SubscribeService.GetSubscription:input_type -> bobobeads.v1.GetSubscriptionRequest
	14, // 25: bobobeads.v1.SubscribeService.ListOrders:input_type -> bobobeads.v1.ListOrdersRequest
	3,  // 26: bobobeads.v1.SubscribeService.ListProducts:output_type -> bobobeads.v1.ListProductsResponse
	5,  // 27: bobobeads.v1.SubscribeService.CreateOrder:output_type -> bobobeads.v1.CreateOrderResponse
	7,  // 28: bobobeads.v1.SubscribeService.GetPaymentParams:output_type -> bobobeads.v1.GetPaymentParamsResponse
	9,  // 29: bobobeads.v1.SubscribeService.PaymentCallback:output_type -> bobobeads.v1.PaymentCallbackResponse
	11, // 30: bobobeads.v1.SubscribeService.RestorePurchase:output_type -> bobobeads.v1.RestorePurchaseResponse
	13, // 31: bobobeads.v1.SubscribeService.GetSubscription:output_type -> bobobeads.v1.GetSubscriptionResponse
	15, // 32: bobobeads.v1.SubscribeService.ListOrders:output_type -> bobobeads.v1.ListOrdersResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_subscribe_proto_init() }
func file_subscribe_proto_init() {
	if File_subscribe_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscribe_proto_rawDesc), len(file_subscribe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscribe_proto_goTypes,
		DependencyIndexes: file_subscribe_proto_depIdxs,
		MessageInfos:      file_subscribe_proto_msgTypes,
	}.Build()
	File_subscribe_proto = out.File
	file_subscribe_proto_goTypes = nil
	file_subscribe_proto_depIdxs = nil
}
