// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAppConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header        *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppConfigRequest) Reset() {
	*x = GetAppConfigRequest{}
	mi := &file_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppConfigRequest) ProtoMessage() {}

func (x *GetAppConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppConfigRequest.ProtoReflect.Descriptor instead.
func (*GetAppConfigRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

func (x *GetAppConfigRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type GetAppConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 应用配置键值。
	Configs       map[string]string `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppConfigResponse) Reset() {
	*x = GetAppConfigResponse{}
	mi := &file_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppConfigResponse) ProtoMessage() {}

func (x *GetAppConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppConfigResponse.ProtoReflect.Descriptor instead.
func (*GetAppConfigResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{1}
}

func (x *GetAppConfigResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetAppConfigResponse) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

type CheckUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 当前应用版本。
	CurrentVersion string `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckUpdateRequest) Reset() {
	*x = CheckUpdateRequest{}
	mi := &file_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdateRequest) ProtoMessage() {}

func (x *CheckUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdateRequest.ProtoReflect.Descriptor instead.
func (*CheckUpdateRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{2}
}

func (x *CheckUpdateRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CheckUpdateRequest) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

type CheckUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 是否有新版本。
	HasUpdate bool `protobuf:"varint,2,opt,name=has_update,json=hasUpdate,proto3" json:"has_update,omitempty"`
	// 是否强制更新。
	ForceUpdate bool `protobuf:"varint,3,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	// 最新版本号。
	LatestVersion string `protobuf:"bytes,4,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	// 下载地址。
	DownloadUrl string `protobuf:"bytes,5,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	// 更新说明。
	ReleaseNotes  string `protobuf:"bytes,6,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUpdateResponse) Reset() {
	*x = CheckUpdateResponse{}
	mi := &file_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdateResponse) ProtoMessage() {}

func (x *CheckUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdateResponse.ProtoReflect.Descriptor instead.
func (*CheckUpdateResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{3}
}

func (x *CheckUpdateResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CheckUpdateResponse) GetHasUpdate() bool {
	if x != nil {
		return x.HasUpdate
	}
	return false
}

func (x *CheckUpdateResponse) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

func (x *CheckUpdateResponse) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *CheckUpdateResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *CheckUpdateResponse) GetReleaseNotes() string {
	if x != nil {
		return x.ReleaseNotes
	}
	return ""
}

type BannerItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Banner ID。
	BannerId string `protobuf:"bytes,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	// Banner 图片地址。
	ImageUrl string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// 跳转类型。
	LinkType string `protobuf:"bytes,3,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`
	// 跳转目标。
	LinkValue string `protobuf:"bytes,4,opt,name=link_value,json=linkValue,proto3" json:"link_value,omitempty"`
	// 排序值。
	SortOrder     int32 `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerItem) Reset() {
	*x = BannerItem{}
	mi := &file_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerItem) ProtoMessage() {}

func (x *BannerItem) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerItem.ProtoReflect.Descriptor instead.
func (*BannerItem) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{4}
}

func (x *BannerItem) GetBannerId() string {
	if x != nil {
		return x.BannerId
	}
	return ""
}

func (x *BannerItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *BannerItem) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

func (x *BannerItem) GetLinkValue() string {
	if x != nil {
		return x.LinkValue
	}
	return ""
}

func (x *BannerItem) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type GetBannersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header        *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBannersRequest) Reset() {
	*x = GetBannersRequest{}
	mi := &file_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBannersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannersRequest) ProtoMessage() {}

func (x *GetBannersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannersRequest.ProtoReflect.Descriptor instead.
func (*GetBannersRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{5}
}

func (x *GetBannersRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type GetBannersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Banner 列表。
	Banners       []*BannerItem `protobuf:"bytes,2,rep,name=banners,proto3" json:"banners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBannersResponse) Reset() {
	*x = GetBannersResponse{}
	mi := &file_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBannersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannersResponse) ProtoMessage() {}

func (x *GetBannersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannersResponse.ProtoReflect.Descriptor instead.
func (*GetBannersResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{6}
}

func (x *GetBannersResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetBannersResponse) GetBanners() []*BannerItem {
	if x != nil {
		return x.Banners
	}
	return nil
}

type BeadBrand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 品牌标识。
	Brand string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	// 品牌展示名。
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// 品牌颜色列表。
	Colors        []*BeadColor `protobuf:"bytes,3,rep,name=colors,proto3" json:"colors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeadBrand) Reset() {
	*x = BeadBrand{}
	mi := &file_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeadBrand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeadBrand) ProtoMessage() {}

func (x *BeadBrand) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeadBrand.ProtoReflect.Descriptor instead.
func (*BeadBrand) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{7}
}

func (x *BeadBrand) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *BeadBrand) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *BeadBrand) GetColors() []*BeadColor {
	if x != nil {
		return x.Colors
	}
	return nil
}

type BeadColor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 色号编码。
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// 颜色名称。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 颜色十六进制值。
	Hex           string `protobuf:"bytes,3,opt,name=hex,proto3" json:"hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeadColor) Reset() {
	*x = BeadColor{}
	mi := &file_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeadColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeadColor) ProtoMessage() {}

func (x *BeadColor) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeadColor.ProtoReflect.Descriptor instead.
func (*BeadColor) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{8}
}

func (x *BeadColor) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BeadColor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BeadColor) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

type GetBeadColorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 品牌筛选。
	Brand         string `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeadColorsRequest) Reset() {
	*x = GetBeadColorsRequest{}
	mi := &file_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeadColorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeadColorsRequest) ProtoMessage() {}

func (x *GetBeadColorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeadColorsRequest.ProtoReflect.Descriptor instead.
func (*GetBeadColorsRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{9}
}

func (x *GetBeadColorsRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetBeadColorsRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

type GetBeadColorsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 品牌颜色分组列表。
	Brands        []*BeadBrand `protobuf:"bytes,2,rep,name=brands,proto3" json:"brands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeadColorsResponse) Reset() {
	*x = GetBeadColorsResponse{}
	mi := &file_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeadColorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeadColorsResponse) ProtoMessage() {}

func (x *GetBeadColorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeadColorsResponse.ProtoReflect.Descriptor instead.
func (*GetBeadColorsResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{10}
}

func (x *GetBeadColorsResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetBeadColorsResponse) GetBrands() []*BeadBrand {
	if x != nil {
		return x.Brands
	}
	return nil
}

type BoardSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 豆板规格 ID。
	SpecId string `protobuf:"bytes,1,opt,name=spec_id,json=specId,proto3" json:"spec_id,omitempty"`
	// 豆板名称。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 豆板形状。
	Shape string `protobuf:"bytes,3,opt,name=shape,proto3" json:"shape,omitempty"`
	// 豆板宽度。
	Width int32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	// 豆板高度。
	Height int32 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	// 拼豆尺寸。
	BeadSize      string `protobuf:"bytes,6,opt,name=bead_size,json=beadSize,proto3" json:"bead_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardSpec) Reset() {
	*x = BoardSpec{}
	mi := &file_system_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardSpec) ProtoMessage() {}

func (x *BoardSpec) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardSpec.ProtoReflect.Descriptor instead.
func (*BoardSpec) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{11}
}

func (x *BoardSpec) GetSpecId() string {
	if x != nil {
		return x.SpecId
	}
	return ""
}

func (x *BoardSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardSpec) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *BoardSpec) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoardSpec) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BoardSpec) GetBeadSize() string {
	if x != nil {
		return x.BeadSize
	}
	return ""
}

type GetBoardSpecsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header        *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardSpecsRequest) Reset() {
	*x = GetBoardSpecsRequest{}
	mi := &file_system_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardSpecsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardSpecsRequest) ProtoMessage() {}

func (x *GetBoardSpecsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardSpecsRequest.ProtoReflect.Descriptor instead.
func (*GetBoardSpecsRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{12}
}

func (x *GetBoardSpecsRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type GetBoardSpecsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 豆板规格列表。
	Specs         []*BoardSpec `protobuf:"bytes,2,rep,name=specs,proto3" json:"specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardSpecsResponse) Reset() {
	*x = GetBoardSpecsResponse{}
	mi := &file_system_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardSpecsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardSpecsResponse) ProtoMessage() {}

func (x *GetBoardSpecsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardSpecsResponse.ProtoReflect.Descriptor instead.
func (*GetBoardSpecsResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{13}
}

func (x *GetBoardSpecsResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetBoardSpecsResponse) GetSpecs() []*BoardSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

var File_system_proto protoreflect.FileDescriptor

const file_system_proto_rawDesc = "" +
	"\n" +
	"\fsystem.proto\x12\fbobobeads.v1\x1a\fcommon.proto\x1a\n" +
	"work.proto\x1a\x1cgoogle/api/annotations.proto\"J\n" +
	"\x13GetAppConfigRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"\xd3\x01\n" +
	"\x14GetAppConfigResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12I\n" +
	"\aconfigs\x18\x02 \x03(\v2/.bobobeads.v1.GetAppConfigResponse.ConfigsEntryR\aconfigs\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x12CheckUpdateRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\tR\x0ecurrentVersion\"\xfc\x01\n" +
	"\x13CheckUpdateResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12\x1d\n" +
	"\n" +
	"has_update\x18\x02 \x01(\bR\thasUpdate\x12!\n" +
	"\fforce_update\x18\x03 \x01(\bR\vforceUpdate\x12%\n" +
	"\x0elatest_version\x18\x04 \x01(\tR\rlatestVersion\x12!\n" +
	"\fdownload_url\x18\x05 \x01(\tR\vdownloadUrl\x12#\n" +
	"\rrelease_notes\x18\x06 \x01(\tR\freleaseNotes\"\xa1\x01\n" +
	"\n" +
	"BannerItem\x12\x1b\n" +
	"\tbanner_id\x18\x01 \x01(\tR\bbannerId\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tlink_type\x18\x03 \x01(\tR\blinkType\x12\x1d\n" +
	"\n" +
	"link_value\x18\x04 \x01(\tR\tlinkValue\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\"H\n" +
	"\x11GetBannersRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"~\n" +
	"\x12GetBannersResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x122\n" +
	"\abanners\x18\x02 \x03(\v2\x18.bobobeads.v1.BannerItemR\abanners\"u\n" +
	"\tBeadBrand\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12/\n" +
	"\x06colors\x18\x03 \x03(\v2\x17.bobobeads.v1.BeadColorR\x06colors\"E\n" +
	"\tBeadColor\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03hex\x18\x03 \x01(\tR\x03hex\"a\n" +
	"\x14GetBeadColorsRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\"~\n" +
	"\x15GetBeadColorsResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12/\n" +
	"\x06brands\x18\x02 \x03(\v2\x17.bobobeads.v1.BeadBrandR\x06brands\"\x99\x01\n" +
	"\tBoardSpec\x12\x17\n" +
	"\aspec_id\x18\x01 \x01(\tR\x06specId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05shape\x18\x03 \x01(\tR\x05shape\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x1b\n" +
	"\tbead_size\x18\x06 \x01(\tR\bbeadSize\"K\n" +
	"\x14GetBoardSpecsRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"|\n" +
	"\x15GetBoardSpecsResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12-\n" +
	"\x05specs\x18\x02 \x03(\v2\x17.bobobeads.v1.BoardSpecR\x05specs2\xe5\x04\n" +
	"\rSystemService\x12t\n" +
	"\fGetAppConfig\x12!.bobobeads.v1.GetAppConfigRequest\x1a\".bobobeads.v1.GetAppConfigResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/system/config\x12q\n" +
	"\vCheckUpdate\x12 .bobobeads.v1.CheckUpdateRequest\x1a!.bobobeads.v1.CheckUpdateResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/system/update\x12o\n" +
	"\n" +
	"GetBanners\x12\x1f.bobobeads.v1.GetBannersRequest\x1a .bobobeads.v1.GetBannersResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/system/banners\x12|\n" +
	"\rGetBeadColors\x12\".bobobeads.v1.GetBeadColorsRequest\x1a#.bobobeads.v1.GetBeadColorsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/system/bead-colors\x12|\n" +
	"\rGetBoardSpecs\x12\".bobobeads.v1.GetBoardSpecsRequest\x1a#.bobobeads.v1.GetBoardSpecsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/system/board-specsB\xa3\x01\n" +
	"\x10com.bobobeads.v1B\vSystemProtoP\x01Z1github.com/zhaojiabo/bobobeads_server/internal/pb\xa2\x02\x03BXX\xaa\x02\fBobobeads.V1\xca\x02\fBobobeads\\V1\xe2\x02\x18Bobobeads\\V1\\GPBMetadata\xea\x02\rBobobeads::V1b\x06proto3"

var (
	file_system_proto_rawDescOnce sync.Once
	file_system_proto_rawDescData []byte
)

func file_system_proto_rawDescGZIP() []byte {
	file_system_proto_rawDescOnce.Do(func() {
		file_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)))
	})
	return file_system_proto_rawDescData
}

var file_system_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_system_proto_goTypes = []any{
	(*GetAppConfigRequest)(nil),   // 0: bobobeads.v1.GetAppConfigRequest
	(*GetAppConfigResponse)(nil),  // 1: bobobeads.v1.GetAppConfigResponse
	(*CheckUpdateRequest)(nil),    // 2: bobobeads.v1.CheckUpdateRequest
	(*CheckUpdateResponse)(nil),   // 3: bobobeads.v1.CheckUpdateResponse
	(*BannerItem)(nil),            // 4: bobobeads.v1.BannerItem
	(*GetBannersRequest)(nil),     // 5: bobobeads.v1.GetBannersRequest
	(*GetBannersResponse)(nil),    // 6: bobobeads.v1.GetBannersResponse
	(*BeadBrand)(nil),             // 7: bobobeads.v1.BeadBrand
	(*BeadColor)(nil),             // 8: bobobeads.v1.BeadColor
	(*GetBeadColorsRequest)(nil),  // 9: bobobeads.v1.GetBeadColorsRequest
	(*GetBeadColorsResponse)(nil), // 10: bobobeads.v1.GetBeadColorsResponse
	(*BoardSpec)(nil),             // 11: bobobeads.v1.BoardSpec
	(*GetBoardSpecsRequest)(nil),  // 12: bobobeads.v1.GetBoardSpecsRequest
	(*GetBoardSpecsResponse)(nil), // 13: bobobeads.v1.GetBoardSpecsResponse
	nil,                           // 14: bobobeads.v1.GetAppConfigResponse.ConfigsEntry
	(*RequestHeader)(nil),         // 15: bobobeads.v1.RequestHeader
	(*ResponseHeader)(nil),        // 16: bobobeads.v1.ResponseHeader
}
var file_system_proto_depIdxs = []int32{
	15, // 0: bobobeads.v1.GetAppConfigRequest.header:type_name -> bobobeads.v1.RequestHeader
	16, // 1: bobobeads.v1.GetAppConfigResponse.header:type_name -> bobobeads.v1.ResponseHeader
	14, // 2: bobobeads.v1.GetAppConfigResponse.configs:type_name -> bobobeads.v1.GetAppConfigResponse.ConfigsEntry
	15, // 3: bobobeads.v1.CheckUpdateRequest.header:type_name -> bobobeads.v1.RequestHeader
	16, // 4: bobobeads.v1.CheckUpdateResponse.header:type_name -> bobobeads.v1.ResponseHeader
	15, // 5: bobobeads.v1.GetBannersRequest.header:type_name -> bobobeads.v1.RequestHeader
	16, // 6: bobobeads.v1.GetBannersResponse.header:type_name -> bobobeads.v1.ResponseHeader
	4,  // 7: bobobeads.v1.GetBannersResponse.banners:type_name -> bobobeads.v1.BannerItem
	8,  // 8: bobobeads.v1.BeadBrand.colors:type_name -> bobobeads.v1.BeadColor
	15, // 9: bobobeads.v1.GetBeadColorsRequest.header:type_name -> bobobeads.v1.RequestHeader
	16, // 10: bobobeads.v1.GetBeadColorsResponse.header:type_name -> bobobeads.v1.ResponseHeader
	7,  // 11: bobobeads.v1.GetBeadColorsResponse.brands:type_name -> bobobeads.v1.BeadBrand
	15, // 12: bobobeads.v1.GetBoardSpecsRequest.header:type_name -> bobobeads.v1.RequestHeader
	16, // 13: bobobeads.v1.GetBoardSpecsResponse.header:type_name -> bobobeads.v1.ResponseHeader
	11, // 14: bobobeads.v1.GetBoardSpecsResponse.specs:type_name -> bobobeads.v1.BoardSpec
	0,  // 15: bobobeads.v1.SystemService.GetAppConfig:input_type -> bobobeads.v1.GetAppConfigRequest
	2,  // 16: bobobeads.v1.SystemService.CheckUpdate:input_type -> bobobeads.v1.CheckUpdateRequest
	5,  // 17: bobobeads.v1.SystemService.GetBanners:input_type -> bobobeads.v1.GetBannersRequest
	9,  // 18: bobobeads.v1.SystemService.GetBeadColors:input_type -> bobobeads.v1.GetBeadColorsRequest
	12, // 19: bobobeads.v1.SystemService.GetBoardSpecs:input_type -> bobobeads.v1.GetBoardSpecsRequest
	1,  // 20: bobobeads.v1.SystemService.GetAppConfig:output_type -> bobobeads.v1.GetAppConfigResponse
	3,  // 21: bobobeads.v1.SystemService.CheckUpdate:output_type -> bobobeads.v1.CheckUpdateResponse
	6,  // 22: bobobeads.v1.SystemService.GetBanners:output_type -> bobobeads.v1.GetBannersResponse
	10, // 23: bobobeads.v1.SystemService.GetBeadColors:output_type -> bobobeads.v1.GetBeadColorsResponse
	13, // 24: bobobeads.v1.SystemService.GetBoardSpecs:output_type -> bobobeads.v1.GetBoardSpecsResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_system_proto_init() }
func file_system_proto_init() {
	if File_system_proto != nil {
		return
	}
	file_common_proto_init()
	file_work_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_proto_goTypes,
		DependencyIndexes: file_system_proto_depIdxs,
		MessageInfos:      file_system_proto_msgTypes,
	}.Build()
	File_system_proto = out.File
	file_system_proto_goTypes = nil
	file_system_proto_depIdxs = nil
}
