// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: system.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemService_GetAppConfig_FullMethodName  = "/bobobeads.v1.SystemService/GetAppConfig"
	SystemService_CheckUpdate_FullMethodName   = "/bobobeads.v1.SystemService/CheckUpdate"
	SystemService_GetBanners_FullMethodName    = "/bobobeads.v1.SystemService/GetBanners"
	SystemService_GetBeadColors_FullMethodName = "/bobobeads.v1.SystemService/GetBeadColors"
	SystemService_GetBoardSpecs_FullMethodName = "/bobobeads.v1.SystemService/GetBoardSpecs"
)

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 系统配置与基础数据服务。
type SystemServiceClient interface {
	// 获取应用配置。
	GetAppConfig(ctx context.Context, in *GetAppConfigRequest, opts ...grpc.CallOption) (*GetAppConfigResponse, error)
	// 检查应用版本更新。
	CheckUpdate(ctx context.Context, in *CheckUpdateRequest, opts ...grpc.CallOption) (*CheckUpdateResponse, error)
	// 获取首页 Banner 列表。
	GetBanners(ctx context.Context, in *GetBannersRequest, opts ...grpc.CallOption) (*GetBannersResponse, error)
	// 获取拼豆颜色库。
	GetBeadColors(ctx context.Context, in *GetBeadColorsRequest, opts ...grpc.CallOption) (*GetBeadColorsResponse, error)
	// 获取豆板规格列表。
	GetBoardSpecs(ctx context.Context, in *GetBoardSpecsRequest, opts ...grpc.CallOption) (*GetBoardSpecsResponse, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) GetAppConfig(ctx context.Context, in *GetAppConfigRequest, opts ...grpc.CallOption) (*GetAppConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppConfigResponse)
	err := c.cc.Invoke(ctx, SystemService_GetAppConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CheckUpdate(ctx context.Context, in *CheckUpdateRequest, opts ...grpc.CallOption) (*CheckUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUpdateResponse)
	err := c.cc.Invoke(ctx, SystemService_CheckUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetBanners(ctx context.Context, in *GetBannersRequest, opts ...grpc.CallOption) (*GetBannersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBannersResponse)
	err := c.cc.Invoke(ctx, SystemService_GetBanners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetBeadColors(ctx context.Context, in *GetBeadColorsRequest, opts ...grpc.CallOption) (*GetBeadColorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBeadColorsResponse)
	err := c.cc.Invoke(ctx, SystemService_GetBeadColors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetBoardSpecs(ctx context.Context, in *GetBoardSpecsRequest, opts ...grpc.CallOption) (*GetBoardSpecsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBoardSpecsResponse)
	err := c.cc.Invoke(ctx, SystemService_GetBoardSpecs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations must embed UnimplementedSystemServiceServer
// for forward compatibility.
//
// 系统配置与基础数据服务。
type SystemServiceServer interface {
	// 获取应用配置。
	GetAppConfig(context.Context, *GetAppConfigRequest) (*GetAppConfigResponse, error)
	// 检查应用版本更新。
	CheckUpdate(context.Context, *CheckUpdateRequest) (*CheckUpdateResponse, error)
	// 获取首页 Banner 列表。
	GetBanners(context.Context, *GetBannersRequest) (*GetBannersResponse, error)
	// 获取拼豆颜色库。
	GetBeadColors(context.Context, *GetBeadColorsRequest) (*GetBeadColorsResponse, error)
	// 获取豆板规格列表。
	GetBoardSpecs(context.Context, *GetBoardSpecsRequest) (*GetBoardSpecsResponse, error)
	mustEmbedUnimplementedSystemServiceServer()
}

// UnimplementedSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemServiceServer struct{}

func (UnimplementedSystemServiceServer) GetAppConfig(context.Context, *GetAppConfigRequest) (*GetAppConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppConfig not implemented")
}
func (UnimplementedSystemServiceServer) CheckUpdate(context.Context, *CheckUpdateRequest) (*CheckUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUpdate not implemented")
}
func (UnimplementedSystemServiceServer) GetBanners(context.Context, *GetBannersRequest) (*GetBannersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBanners not implemented")
}
func (UnimplementedSystemServiceServer) GetBeadColors(context.Context, *GetBeadColorsRequest) (*GetBeadColorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBeadColors not implemented")
}
func (UnimplementedSystemServiceServer) GetBoardSpecs(context.Context, *GetBoardSpecsRequest) (*GetBoardSpecsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBoardSpecs not implemented")
}
func (UnimplementedSystemServiceServer) mustEmbedUnimplementedSystemServiceServer() {}
func (UnimplementedSystemServiceServer) testEmbeddedByValue()                       {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_GetAppConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetAppConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetAppConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetAppConfig(ctx, req.(*GetAppConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CheckUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CheckUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_CheckUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CheckUpdate(ctx, req.(*CheckUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetBanners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetBanners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetBanners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetBanners(ctx, req.(*GetBannersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetBeadColors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBeadColorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetBeadColors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetBeadColors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetBeadColors(ctx, req.(*GetBeadColorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetBoardSpecs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoardSpecsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetBoardSpecs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetBoardSpecs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetBoardSpecs(ctx, req.(*GetBoardSpecsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bobobeads.v1.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppConfig",
			Handler:    _SystemService_GetAppConfig_Handler,
		},
		{
			MethodName: "CheckUpdate",
			Handler:    _SystemService_CheckUpdate_Handler,
		},
		{
			MethodName: "GetBanners",
			Handler:    _SystemService_GetBanners_Handler,
		},
		{
			MethodName: "GetBeadColors",
			Handler:    _SystemService_GetBeadColors_Handler,
		},
		{
			MethodName: "GetBoardSpecs",
			Handler:    _SystemService_GetBoardSpecs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}
