// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: template.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl       string                 `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	TemplateCount int32                  `protobuf:"varint,4,opt,name=template_count,json=templateCount,proto3" json:"template_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryItem) Reset() {
	*x = CategoryItem{}
	mi := &file_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryItem) ProtoMessage() {}

func (x *CategoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryItem.ProtoReflect.Descriptor instead.
func (*CategoryItem) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryItem) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryItem) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *CategoryItem) GetTemplateCount() int32 {
	if x != nil {
		return x.TemplateCount
	}
	return 0
}

type TemplateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PreviewUrl    string                 `protobuf:"bytes,3,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	BoardSpec     string                 `protobuf:"bytes,4,opt,name=board_spec,json=boardSpec,proto3" json:"board_spec,omitempty"`
	ColorCount    int32                  `protobuf:"varint,5,opt,name=color_count,json=colorCount,proto3" json:"color_count,omitempty"`
	IsFree        bool                   `protobuf:"varint,6,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	CreditCost    int32                  `protobuf:"varint,7,opt,name=credit_cost,json=creditCost,proto3" json:"credit_cost,omitempty"`
	DownloadCount int32                  `protobuf:"varint,8,opt,name=download_count,json=downloadCount,proto3" json:"download_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateItem) Reset() {
	*x = TemplateItem{}
	mi := &file_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateItem) ProtoMessage() {}

func (x *TemplateItem) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateItem.ProtoReflect.Descriptor instead.
func (*TemplateItem) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateItem) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *TemplateItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TemplateItem) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *TemplateItem) GetBoardSpec() string {
	if x != nil {
		return x.BoardSpec
	}
	return ""
}

func (x *TemplateItem) GetColorCount() int32 {
	if x != nil {
		return x.ColorCount
	}
	return 0
}

func (x *TemplateItem) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *TemplateItem) GetCreditCost() int32 {
	if x != nil {
		return x.CreditCost
	}
	return 0
}

func (x *TemplateItem) GetDownloadCount() int32 {
	if x != nil {
		return x.DownloadCount
	}
	return 0
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{2}
}

func (x *ListCategoriesRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Categories    []*CategoryItem        `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{3}
}

func (x *ListCategoriesResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListCategoriesResponse) GetCategories() []*CategoryItem {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_template_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{4}
}

func (x *ListTemplatesRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListTemplatesRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListTemplatesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Templates     []*TemplateItem        `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_template_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{5}
}

func (x *ListTemplatesResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListTemplatesResponse) GetTemplates() []*TemplateItem {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_template_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{6}
}

func (x *GetTemplateRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type GetTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Template      *TemplateItem          `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	PatternData   *PatternData           `protobuf:"bytes,3,opt,name=pattern_data,json=patternData,proto3" json:"pattern_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateResponse) Reset() {
	*x = GetTemplateResponse{}
	mi := &file_template_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResponse) ProtoMessage() {}

func (x *GetTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{7}
}

func (x *GetTemplateResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetTemplateResponse) GetTemplate() *TemplateItem {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *GetTemplateResponse) GetPatternData() *PatternData {
	if x != nil {
		return x.PatternData
	}
	return nil
}

var File_template_proto protoreflect.FileDescriptor

const file_template_proto_rawDesc = "" +
	"\n" +
	"\x0etemplate.proto\x12\fbobobeads.v1\x1a\fcommon.proto\x1a\n" +
	"work.proto\x1a\x1cgoogle/api/annotations.proto\"\x85\x01\n" +
	"\fCategoryItem\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12%\n" +
	"\x0etemplate_count\x18\x04 \x01(\x05R\rtemplateCount\"\x87\x02\n" +
	"\fTemplateItem\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vpreview_url\x18\x03 \x01(\tR\n" +
	"previewUrl\x12\x1d\n" +
	"\n" +
	"board_spec\x18\x04 \x01(\tR\tboardSpec\x12\x1f\n" +
	"\vcolor_count\x18\x05 \x01(\x05R\n" +
	"colorCount\x12\x17\n" +
	"\ais_free\x18\x06 \x01(\bR\x06isFree\x12\x1f\n" +
	"\vcredit_cost\x18\a \x01(\x05R\n" +
	"creditCost\x12%\n" +
	"\x0edownload_count\x18\b \x01(\x05R\rdownloadCount\"L\n" +
	"\x15ListCategoriesRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"\x8a\x01\n" +
	"\x16ListCategoriesResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12:\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x1a.bobobeads.v1.CategoryItemR\n" +
	"categories\"\x9b\x01\n" +
	"\x14ListTemplatesRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\x12-\n" +
	"\x04page\x18\x03 \x01(\v2\x19.bobobeads.v1.PageRequestR\x04page\"\xb7\x01\n" +
	"\x15ListTemplatesResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x128\n" +
	"\ttemplates\x18\x02 \x03(\v2\x1a.bobobeads.v1.TemplateItemR\ttemplates\x12.\n" +
	"\x04page\x18\x03 \x01(\v2\x1a.bobobeads.v1.PageResponseR\x04page\"j\n" +
	"\x12GetTemplateRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\"\xc1\x01\n" +
	"\x13GetTemplateResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x126\n" +
	"\btemplate\x18\x02 \x01(\v2\x1a.bobobeads.v1.TemplateItemR\btemplate\x12<\n" +
	"\fpattern_data\x18\x03 \x01(\v2\x19.bobobeads.v1.PatternDataR\vpatternData2\x87\x03\n" +
	"\x0fTemplateService\x12\x81\x01\n" +
	"\x0eListCategories\x12#.bobobeads.v1.ListCategoriesRequest\x1a$.bobobeads.v1.ListCategoriesResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/templates/categories\x12s\n" +
	"\rListTemplates\x12\".bobobeads.v1.ListTemplatesRequest\x1a#.bobobeads.v1.ListTemplatesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/templates\x12{\n" +
	"\vGetTemplate\x12 .bobobeads.v1.GetTemplateRequest\x1a!.bobobeads.v1.GetTemplateResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/templates/{template_id}B\xa5\x01\n" +
	"\x10com.bobobeads.v1B\rTemplateProtoP\x01Z1github.com/zhaojiabo/bobobeads_server/internal/pb\xa2\x02\x03BXX\xaa\x02\fBobobeads.V1\xca\x02\fBobobeads\\V1\xe2\x02\x18Bobobeads\\V1\\GPBMetadata\xea\x02\rBobobeads::V1b\x06proto3"

var (
	file_template_proto_rawDescOnce sync.Once
	file_template_proto_rawDescData []byte
)

func file_template_proto_rawDescGZIP() []byte {
	file_template_proto_rawDescOnce.Do(func() {
		file_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_template_proto_rawDesc), len(file_template_proto_rawDesc)))
	})
	return file_template_proto_rawDescData
}

var file_template_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_template_proto_goTypes = []any{
	(*CategoryItem)(nil),           // 0: bobobeads.v1.CategoryItem
	(*TemplateItem)(nil),           // 1: bobobeads.v1.TemplateItem
	(*ListCategoriesRequest)(nil),  // 2: bobobeads.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil), // 3: bobobeads.v1.ListCategoriesResponse
	(*ListTemplatesRequest)(nil),   // 4: bobobeads.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),  // 5: bobobeads.v1.ListTemplatesResponse
	(*GetTemplateRequest)(nil),     // 6: bobobeads.v1.GetTemplateRequest
	(*GetTemplateResponse)(nil),    // 7: bobobeads.v1.GetTemplateResponse
	(*RequestHeader)(nil),          // 8: bobobeads.v1.RequestHeader
	(*ResponseHeader)(nil),         // 9: bobobeads.v1.ResponseHeader
	(*PageRequest)(nil),            // 10: bobobeads.v1.PageRequest
	(*PageResponse)(nil),           // 11: bobobeads.v1.PageResponse
	(*PatternData)(nil),            // 12: bobobeads.v1.PatternData
}
var file_template_proto_depIdxs = []int32{
	8,  // 0: bobobeads.v1.ListCategoriesRequest.header:type_name -> bobobeads.v1.RequestHeader
	9,  // 1: bobobeads.v1.ListCategoriesResponse.header:type_name -> bobobeads.v1.ResponseHeader
	0,  // 2: bobobeads.v1.ListCategoriesResponse.categories:type_name -> bobobeads.v1.CategoryItem
	8,  // 3: bobobeads.v1.ListTemplatesRequest.header:type_name -> bobobeads.v1.RequestHeader
	10, // 4: bobobeads.v1.ListTemplatesRequest.page:type_name -> bobobeads.v1.PageRequest
	9,  // 5: bobobeads.v1.ListTemplatesResponse.header:type_name -> bobobeads.v1.ResponseHeader
	1,  // 6: bobobeads.v1.ListTemplatesResponse.templates:type_name -> bobobeads.v1.TemplateItem
	11, // 7: bobobeads.v1.ListTemplatesResponse.page:type_name -> bobobeads.v1.PageResponse
	8,  // 8: bobobeads.v1.GetTemplateRequest.header:type_name -> bobobeads.v1.RequestHeader
	9,  // 9: bobobeads.v1.GetTemplateResponse.header:type_name -> bobobeads.v1.ResponseHeader
	1,  // 10: bobobeads.v1.GetTemplateResponse.template:type_name -> bobobeads.v1.TemplateItem
	12, // 11: bobobeads.v1.GetTemplateResponse.pattern_data:type_name -> bobobeads.v1.PatternData
	2,  // 12: bobobeads.v1.TemplateService.ListCategories:input_type -> bobobeads.v1.ListCategoriesRequest
	4,  // 13: bobobeads.v1.TemplateService.ListTemplates:input_type -> bobobeads.v1.ListTemplatesRequest
	6,  // 14: bobobeads.v1.TemplateService.GetTemplate:input_type -> bobobeads.v1.GetTemplateRequest
	3,  // 15: bobobeads.v1.TemplateService.ListCategories:output_type -> bobobeads.v1.ListCategoriesResponse
	5,  // 16: bobobeads.v1.TemplateService.ListTemplates:output_type -> bobobeads.v1.ListTemplatesResponse
	7,  // 17: bobobeads.v1.TemplateService.GetTemplate:output_type -> bobobeads.v1.GetTemplateResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_template_proto_init() }
func file_template_proto_init() {
	if File_template_proto != nil {
		return
	}
	file_common_proto_init()
	file_work_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_template_proto_rawDesc), len(file_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_template_proto_goTypes,
		DependencyIndexes: file_template_proto_depIdxs,
		MessageInfos:      file_template_proto_msgTypes,
	}.Build()
	File_template_proto = out.File
	file_template_proto_goTypes = nil
	file_template_proto_depIdxs = nil
}
