// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: template.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分类 ID。
	CategoryId int32 `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// 分类名称。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 分类图标地址。
	IconUrl string `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	// 分类下图纸数量。
	TemplateCount int32 `protobuf:"varint,4,opt,name=template_count,json=templateCount,proto3" json:"template_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryItem) Reset() {
	*x = CategoryItem{}
	mi := &file_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryItem) ProtoMessage() {}

func (x *CategoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryItem.ProtoReflect.Descriptor instead.
func (*CategoryItem) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryItem) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryItem) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *CategoryItem) GetTemplateCount() int32 {
	if x != nil {
		return x.TemplateCount
	}
	return 0
}

type TemplateItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 图纸 ID。
	TemplateId string `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// 图纸标题。
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 预览图地址。
	PreviewUrl string `protobuf:"bytes,3,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	// 豆板规格。
	BoardSpec string `protobuf:"bytes,4,opt,name=board_spec,json=boardSpec,proto3" json:"board_spec,omitempty"`
	// 颜色数量。
	ColorCount int32 `protobuf:"varint,5,opt,name=color_count,json=colorCount,proto3" json:"color_count,omitempty"`
	// 是否免费。
	IsFree bool `protobuf:"varint,6,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	// 兑换所需积分。
	CreditCost int32 `protobuf:"varint,7,opt,name=credit_cost,json=creditCost,proto3" json:"credit_cost,omitempty"`
	// 下载次数。
	DownloadCount int32 `protobuf:"varint,8,opt,name=download_count,json=downloadCount,proto3" json:"download_count,omitempty"`
	// 缩略图地址。
	ThumbnailUrl string `protobuf:"bytes,9,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	// 图纸描述。
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	// 标签列表。
	Tags []string `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	// 难度等级。
	Difficulty int32 `protobuf:"varint,12,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	// 收藏数量。
	FavoriteCount int32 `protobuf:"varint,13,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	// 当前用户是否已收藏。
	IsFavorited bool `protobuf:"varint,14,opt,name=is_favorited,json=isFavorited,proto3" json:"is_favorited,omitempty"`
	// 图纸宽度。
	Width int32 `protobuf:"varint,15,opt,name=width,proto3" json:"width,omitempty"`
	// 图纸高度。
	Height int32 `protobuf:"varint,16,opt,name=height,proto3" json:"height,omitempty"`
	// 投稿人昵称，发布时的快照；官方自建图纸为空。
	ContributorNickname string `protobuf:"bytes,17,opt,name=contributor_nickname,json=contributorNickname,proto3" json:"contributor_nickname,omitempty"`
	// 所属分类 ID。客户端按它映射本地的图案与文案。
	CategoryId int32 `protobuf:"varint,18,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// 所属分类名称。盲盒专用分类不出现在 ListCategories 里，客户端无法自行用
	// 分类导航的结果翻译 ID，所以名称随图纸一起下发，作为未内置分类的兜底展示。
	CategoryName  string `protobuf:"bytes,19,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateItem) Reset() {
	*x = TemplateItem{}
	mi := &file_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateItem) ProtoMessage() {}

func (x *TemplateItem) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateItem.ProtoReflect.Descriptor instead.
func (*TemplateItem) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateItem) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *TemplateItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TemplateItem) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *TemplateItem) GetBoardSpec() string {
	if x != nil {
		return x.BoardSpec
	}
	return ""
}

func (x *TemplateItem) GetColorCount() int32 {
	if x != nil {
		return x.ColorCount
	}
	return 0
}

func (x *TemplateItem) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *TemplateItem) GetCreditCost() int32 {
	if x != nil {
		return x.CreditCost
	}
	return 0
}

func (x *TemplateItem) GetDownloadCount() int32 {
	if x != nil {
		return x.DownloadCount
	}
	return 0
}

func (x *TemplateItem) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *TemplateItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TemplateItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TemplateItem) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *TemplateItem) GetFavoriteCount() int32 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *TemplateItem) GetIsFavorited() bool {
	if x != nil {
		return x.IsFavorited
	}
	return false
}

func (x *TemplateItem) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TemplateItem) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TemplateItem) GetContributorNickname() string {
	if x != nil {
		return x.ContributorNickname
	}
	return ""
}

func (x *TemplateItem) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *TemplateItem) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type ListCategoriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header        *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{2}
}

func (x *ListCategoriesRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type ListCategoriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 分类列表。
	Categories    []*CategoryItem `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{3}
}

func (x *ListCategoriesResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListCategoriesResponse) GetCategories() []*CategoryItem {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListTemplatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 分类 ID。
	CategoryId int32 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// 分页参数。
	Page *PageRequest `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	// 场景筛选。
	Scene string `protobuf:"bytes,4,opt,name=scene,proto3" json:"scene,omitempty"`
	// 搜索关键词。
	Keyword       string `protobuf:"bytes,5,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_template_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{4}
}

func (x *ListTemplatesRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListTemplatesRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListTemplatesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListTemplatesRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *ListTemplatesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListTemplatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 图纸列表。
	Templates []*TemplateItem `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	// 分页信息。
	Page          *PageResponse `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_template_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{5}
}

func (x *ListTemplatesResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListTemplatesResponse) GetTemplates() []*TemplateItem {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetTemplateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 图纸 ID。
	TemplateId    string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_template_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{6}
}

func (x *GetTemplateRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type GetTemplateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 图纸信息。
	Template *TemplateItem `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	// 图纸数据。
	PatternData   *PatternData `protobuf:"bytes,3,opt,name=pattern_data,json=patternData,proto3" json:"pattern_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateResponse) Reset() {
	*x = GetTemplateResponse{}
	mi := &file_template_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResponse) ProtoMessage() {}

func (x *GetTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{7}
}

func (x *GetTemplateResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetTemplateResponse) GetTemplate() *TemplateItem {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *GetTemplateResponse) GetPatternData() *PatternData {
	if x != nil {
		return x.PatternData
	}
	return nil
}

type FavoriteTemplateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 图纸 ID。
	TemplateId    string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteTemplateRequest) Reset() {
	*x = FavoriteTemplateRequest{}
	mi := &file_template_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteTemplateRequest) ProtoMessage() {}

func (x *FavoriteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteTemplateRequest.ProtoReflect.Descriptor instead.
func (*FavoriteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{8}
}

func (x *FavoriteTemplateRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FavoriteTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type FavoriteTemplateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 当前是否已收藏。
	IsFavorited bool `protobuf:"varint,2,opt,name=is_favorited,json=isFavorited,proto3" json:"is_favorited,omitempty"`
	// 收藏数量。
	FavoriteCount int32 `protobuf:"varint,3,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteTemplateResponse) Reset() {
	*x = FavoriteTemplateResponse{}
	mi := &file_template_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteTemplateResponse) ProtoMessage() {}

func (x *FavoriteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteTemplateResponse.ProtoReflect.Descriptor instead.
func (*FavoriteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{9}
}

func (x *FavoriteTemplateResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FavoriteTemplateResponse) GetIsFavorited() bool {
	if x != nil {
		return x.IsFavorited
	}
	return false
}

func (x *FavoriteTemplateResponse) GetFavoriteCount() int32 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

type UnfavoriteTemplateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 图纸 ID。
	TemplateId    string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfavoriteTemplateRequest) Reset() {
	*x = UnfavoriteTemplateRequest{}
	mi := &file_template_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfavoriteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfavoriteTemplateRequest) ProtoMessage() {}

func (x *UnfavoriteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfavoriteTemplateRequest.ProtoReflect.Descriptor instead.
func (*UnfavoriteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{10}
}

func (x *UnfavoriteTemplateRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UnfavoriteTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type UnfavoriteTemplateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 当前是否已收藏。
	IsFavorited bool `protobuf:"varint,2,opt,name=is_favorited,json=isFavorited,proto3" json:"is_favorited,omitempty"`
	// 收藏数量。
	FavoriteCount int32 `protobuf:"varint,3,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfavoriteTemplateResponse) Reset() {
	*x = UnfavoriteTemplateResponse{}
	mi := &file_template_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfavoriteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfavoriteTemplateResponse) ProtoMessage() {}

func (x *UnfavoriteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfavoriteTemplateResponse.ProtoReflect.Descriptor instead.
func (*UnfavoriteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{11}
}

func (x *UnfavoriteTemplateResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UnfavoriteTemplateResponse) GetIsFavorited() bool {
	if x != nil {
		return x.IsFavorited
	}
	return false
}

func (x *UnfavoriteTemplateResponse) GetFavoriteCount() int32 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

type ListFavoriteTemplatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 分页参数。
	Page *PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	// 分类 ID，0 或不传表示全部分类。
	CategoryId    int32 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoriteTemplatesRequest) Reset() {
	*x = ListFavoriteTemplatesRequest{}
	mi := &file_template_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoriteTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoriteTemplatesRequest) ProtoMessage() {}

func (x *ListFavoriteTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoriteTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListFavoriteTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{12}
}

func (x *ListFavoriteTemplatesRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListFavoriteTemplatesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListFavoriteTemplatesRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type ListFavoriteTemplatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 收藏图纸列表。
	Templates []*TemplateItem `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	// 分页信息。
	Page          *PageResponse `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoriteTemplatesResponse) Reset() {
	*x = ListFavoriteTemplatesResponse{}
	mi := &file_template_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoriteTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoriteTemplatesResponse) ProtoMessage() {}

func (x *ListFavoriteTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoriteTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListFavoriteTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{13}
}

func (x *ListFavoriteTemplatesResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListFavoriteTemplatesResponse) GetTemplates() []*TemplateItem {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListFavoriteTemplatesResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListFavoriteCategoriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header        *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoriteCategoriesRequest) Reset() {
	*x = ListFavoriteCategoriesRequest{}
	mi := &file_template_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoriteCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoriteCategoriesRequest) ProtoMessage() {}

func (x *ListFavoriteCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoriteCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListFavoriteCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{14}
}

func (x *ListFavoriteCategoriesRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type ListFavoriteCategoriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 分类列表，template_count 为当前用户在该分类下的收藏数量。
	Categories    []*CategoryItem `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoriteCategoriesResponse) Reset() {
	*x = ListFavoriteCategoriesResponse{}
	mi := &file_template_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoriteCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoriteCategoriesResponse) ProtoMessage() {}

func (x *ListFavoriteCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoriteCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListFavoriteCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{15}
}

func (x *ListFavoriteCategoriesResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListFavoriteCategoriesResponse) GetCategories() []*CategoryItem {
	if x != nil {
		return x.Categories
	}
	return nil
}

type RandomTemplateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header        *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomTemplateRequest) Reset() {
	*x = RandomTemplateRequest{}
	mi := &file_template_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomTemplateRequest) ProtoMessage() {}

func (x *RandomTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomTemplateRequest.ProtoReflect.Descriptor instead.
func (*RandomTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{16}
}

func (x *RandomTemplateRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type RandomTemplateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 随机图纸信息。
	Template *TemplateItem `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	// 图纸数据。
	PatternData *PatternData `protobuf:"bytes,3,opt,name=pattern_data,json=patternData,proto3" json:"pattern_data,omitempty"`
	// 抽取后的当日额度状况，客户端可直接刷新剩余次数，无需再调 GetBlindBoxQuota。
	Quota         *BlindBoxQuota `protobuf:"bytes,4,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomTemplateResponse) Reset() {
	*x = RandomTemplateResponse{}
	mi := &file_template_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomTemplateResponse) ProtoMessage() {}

func (x *RandomTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomTemplateResponse.ProtoReflect.Descriptor instead.
func (*RandomTemplateResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{17}
}

func (x *RandomTemplateResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RandomTemplateResponse) GetTemplate() *TemplateItem {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *RandomTemplateResponse) GetPatternData() *PatternData {
	if x != nil {
		return x.PatternData
	}
	return nil
}

func (x *RandomTemplateResponse) GetQuota() *BlindBoxQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

// BlindBoxQuota 描述用户当天的盲盒次数。次数用尽时抽取接口返回 2007
// （CodeBlindBoxQuotaUsedUp），客户端应据此提示到次日恢复，而不是当普通错误重试。
type BlindBoxQuota struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 今日总次数上限。
	DailyLimit int32 `protobuf:"varint,1,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	// 今日已用次数。
	Used int32 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	// 今日剩余次数。
	Remaining int32 `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// 下次重置时间，Unix 秒。按固定的东八区零点计算。
	ResetAt       int64 `protobuf:"varint,4,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlindBoxQuota) Reset() {
	*x = BlindBoxQuota{}
	mi := &file_template_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlindBoxQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxQuota) ProtoMessage() {}

func (x *BlindBoxQuota) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxQuota.ProtoReflect.Descriptor instead.
func (*BlindBoxQuota) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{18}
}

func (x *BlindBoxQuota) GetDailyLimit() int32 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *BlindBoxQuota) GetUsed() int32 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *BlindBoxQuota) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *BlindBoxQuota) GetResetAt() int64 {
	if x != nil {
		return x.ResetAt
	}
	return 0
}

type GetBlindBoxQuotaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header        *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlindBoxQuotaRequest) Reset() {
	*x = GetBlindBoxQuotaRequest{}
	mi := &file_template_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlindBoxQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlindBoxQuotaRequest) ProtoMessage() {}

func (x *GetBlindBoxQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlindBoxQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetBlindBoxQuotaRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{19}
}

func (x *GetBlindBoxQuotaRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type GetBlindBoxQuotaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 当日额度状况。
	Quota         *BlindBoxQuota `protobuf:"bytes,2,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlindBoxQuotaResponse) Reset() {
	*x = GetBlindBoxQuotaResponse{}
	mi := &file_template_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlindBoxQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlindBoxQuotaResponse) ProtoMessage() {}

func (x *GetBlindBoxQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlindBoxQuotaResponse.ProtoReflect.Descriptor instead.
func (*GetBlindBoxQuotaResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{20}
}

func (x *GetBlindBoxQuotaResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetBlindBoxQuotaResponse) GetQuota() *BlindBoxQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

type ListBlindBoxRecordsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 分页参数。
	Page          *PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlindBoxRecordsRequest) Reset() {
	*x = ListBlindBoxRecordsRequest{}
	mi := &file_template_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlindBoxRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlindBoxRecordsRequest) ProtoMessage() {}

func (x *ListBlindBoxRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlindBoxRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListBlindBoxRecordsRequest) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{21}
}

func (x *ListBlindBoxRecordsRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListBlindBoxRecordsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListBlindBoxRecordsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 图纸列表。
	Templates []*TemplateItem `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	// 分页信息。
	Page          *PageResponse `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlindBoxRecordsResponse) Reset() {
	*x = ListBlindBoxRecordsResponse{}
	mi := &file_template_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlindBoxRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlindBoxRecordsResponse) ProtoMessage() {}

func (x *ListBlindBoxRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlindBoxRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListBlindBoxRecordsResponse) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{22}
}

func (x *ListBlindBoxRecordsResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListBlindBoxRecordsResponse) GetTemplates() []*TemplateItem {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListBlindBoxRecordsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_template_proto protoreflect.FileDescriptor

const file_template_proto_rawDesc = "" +
	"\n" +
	"\x0etemplate.proto\x12\fbobobeads.v1\x1a\fcommon.proto\x1a\n" +
	"work.proto\x1a\x1cgoogle/api/annotations.proto\"\x85\x01\n" +
	"\fCategoryItem\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12%\n" +
	"\x0etemplate_count\x18\x04 \x01(\x05R\rtemplateCount\"\xf3\x04\n" +
	"\fTemplateItem\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vpreview_url\x18\x03 \x01(\tR\n" +
	"previewUrl\x12\x1d\n" +
	"\n" +
	"board_spec\x18\x04 \x01(\tR\tboardSpec\x12\x1f\n" +
	"\vcolor_count\x18\x05 \x01(\x05R\n" +
	"colorCount\x12\x17\n" +
	"\ais_free\x18\x06 \x01(\bR\x06isFree\x12\x1f\n" +
	"\vcredit_cost\x18\a \x01(\x05R\n" +
	"creditCost\x12%\n" +
	"\x0edownload_count\x18\b \x01(\x05R\rdownloadCount\x12#\n" +
	"\rthumbnail_url\x18\t \x01(\tR\fthumbnailUrl\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"difficulty\x18\f \x01(\x05R\n" +
	"difficulty\x12%\n" +
	"\x0efavorite_count\x18\r \x01(\x05R\rfavoriteCount\x12!\n" +
	"\fis_favorited\x18\x0e \x01(\bR\visFavorited\x12\x14\n" +
	"\x05width\x18\x0f \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x10 \x01(\x05R\x06height\x121\n" +
	"\x14contributor_nickname\x18\x11 \x01(\tR\x13contributorNickname\x12\x1f\n" +
	"\vcategory_id\x18\x12 \x01(\x05R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x13 \x01(\tR\fcategoryName\"L\n" +
	"\x15ListCategoriesRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"\x8a\x01\n" +
	"\x16ListCategoriesResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12:\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x1a.bobobeads.v1.CategoryItemR\n" +
	"categories\"\xcb\x01\n" +
	"\x14ListTemplatesRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\x12-\n" +
	"\x04page\x18\x03 \x01(\v2\x19.bobobeads.v1.PageRequestR\x04page\x12\x14\n" +
	"\x05scene\x18\x04 \x01(\tR\x05scene\x12\x18\n" +
	"\akeyword\x18\x05 \x01(\tR\akeyword\"\xb7\x01\n" +
	"\x15ListTemplatesResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x128\n" +
	"\ttemplates\x18\x02 \x03(\v2\x1a.bobobeads.v1.TemplateItemR\ttemplates\x12.\n" +
	"\x04page\x18\x03 \x01(\v2\x1a.bobobeads.v1.PageResponseR\x04page\"j\n" +
	"\x12GetTemplateRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\"\xc1\x01\n" +
	"\x13GetTemplateResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x126\n" +
	"\btemplate\x18\x02 \x01(\v2\x1a.bobobeads.v1.TemplateItemR\btemplate\x12<\n" +
	"\fpattern_data\x18\x03 \x01(\v2\x19.bobobeads.v1.PatternDataR\vpatternData\"o\n" +
	"\x17FavoriteTemplateRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\"\x9a\x01\n" +
	"\x18FavoriteTemplateResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12!\n" +
	"\fis_favorited\x18\x02 \x01(\bR\visFavorited\x12%\n" +
	"\x0efavorite_count\x18\x03 \x01(\x05R\rfavoriteCount\"q\n" +
	"\x19UnfavoriteTemplateRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\"\x9c\x01\n" +
	"\x1aUnfavoriteTemplateResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12!\n" +
	"\fis_favorited\x18\x02 \x01(\bR\visFavorited\x12%\n" +
	"\x0efavorite_count\x18\x03 \x01(\x05R\rfavoriteCount\"\xa3\x01\n" +
	"\x1cListFavoriteTemplatesRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12-\n" +
	"\x04page\x18\x02 \x01(\v2\x19.bobobeads.v1.PageRequestR\x04page\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x05R\n" +
	"categoryId\"\xbf\x01\n" +
	"\x1dListFavoriteTemplatesResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x128\n" +
	"\ttemplates\x18\x02 \x03(\v2\x1a.bobobeads.v1.TemplateItemR\ttemplates\x12.\n" +
	"\x04page\x18\x03 \x01(\v2\x1a.bobobeads.v1.PageResponseR\x04page\"T\n" +
	"\x1dListFavoriteCategoriesRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"\x92\x01\n" +
	"\x1eListFavoriteCategoriesResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12:\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x1a.bobobeads.v1.CategoryItemR\n" +
	"categories\"L\n" +
	"\x15RandomTemplateRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"\xf7\x01\n" +
	"\x16RandomTemplateResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x126\n" +
	"\btemplate\x18\x02 \x01(\v2\x1a.bobobeads.v1.TemplateItemR\btemplate\x12<\n" +
	"\fpattern_data\x18\x03 \x01(\v2\x19.bobobeads.v1.PatternDataR\vpatternData\x121\n" +
	"\x05quota\x18\x04 \x01(\v2\x1b.bobobeads.v1.BlindBoxQuotaR\x05quota\"}\n" +
	"\rBlindBoxQuota\x12\x1f\n" +
	"\vdaily_limit\x18\x01 \x01(\x05R\n" +
	"dailyLimit\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x05R\x04used\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x05R\tremaining\x12\x19\n" +
	"\breset_at\x18\x04 \x01(\x03R\aresetAt\"N\n" +
	"\x17GetBlindBoxQuotaRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"\x83\x01\n" +
	"\x18GetBlindBoxQuotaResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x121\n" +
	"\x05quota\x18\x02 \x01(\v2\x1b.bobobeads.v1.BlindBoxQuotaR\x05quota\"\x80\x01\n" +
	"\x1aListBlindBoxRecordsRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12-\n" +
	"\x04page\x18\x02 \x01(\v2\x19.bobobeads.v1.PageRequestR\x04page\"\xbd\x01\n" +
	"\x1bListBlindBoxRecordsResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x128\n" +
	"\ttemplates\x18\x02 \x03(\v2\x1a.bobobeads.v1.TemplateItemR\ttemplates\x12.\n" +
	"\x04page\x18\x03 \x01(\v2\x1a.bobobeads.v1.PageResponseR\x04page2\x9c\v\n" +
	"\x0fTemplateService\x12{\n" +
	"\vGetTemplate\x12 .bobobeads.v1.GetTemplateRequest\x1a!.bobobeads.v1.GetTemplateResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/templates/{template_id}\x12s\n" +
	"\rListTemplates\x12\".bobobeads.v1.ListTemplatesRequest\x1a#.bobobeads.v1.ListTemplatesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/templates\x12\x81\x01\n" +
	"\x0eListCategories\x12#.bobobeads.v1.ListCategoriesRequest\x1a$.bobobeads.v1.ListCategoriesResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/templates/categories\x12\x95\x01\n" +
	"\x15ListFavoriteTemplates\x12*.bobobeads.v1.ListFavoriteTemplatesRequest\x1a+.bobobeads.v1.ListFavoriteTemplatesResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/templates/favorites\x12\xa3\x01\n" +
	"\x16ListFavoriteCategories\x12+.bobobeads.v1.ListFavoriteCategoriesRequest\x1a,.bobobeads.v1.ListFavoriteCategoriesResponse\".\x82\xd3\xe4\x93\x02(\x12&/api/v1/templates/favorites/categories\x12\x96\x01\n" +
	"\x10FavoriteTemplate\x12%.bobobeads.v1.FavoriteTemplateRequest\x1a&.bobobeads.v1.FavoriteTemplateResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/api/v1/templates/{template_id}/favorite\x12\x99\x01\n" +
	"\x12UnfavoriteTemplate\x12'.bobobeads.v1.UnfavoriteTemplateRequest\x1a(.bobobeads.v1.UnfavoriteTemplateResponse\"0\x82\xd3\xe4\x93\x02**(/api/v1/templates/{template_id}/favorite\x12}\n" +
	"\x0eRandomTemplate\x12#.bobobeads.v1.RandomTemplateRequest\x1a$.bobobeads.v1.RandomTemplateResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/templates/random\x12\x94\x01\n" +
	"\x13ListBlindBoxRecords\x12(.bobobeads.v1.ListBlindBoxRecordsRequest\x1a).bobobeads.v1.ListBlindBoxRecordsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/templates/random/history\x12\x89\x01\n" +
	"\x10GetBlindBoxQuota\x12%.bobobeads.v1.GetBlindBoxQuotaRequest\x1a&.bobobeads.v1.GetBlindBoxQuotaResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/templates/random/quotaB\xa5\x01\n" +
	"\x10com.bobobeads.v1B\rTemplateProtoP\x01Z1github.com/zhaojiabo/bobobeads_server/internal/pb\xa2\x02\x03BXX\xaa\x02\fBobobeads.V1\xca\x02\fBobobeads\\V1\xe2\x02\x18Bobobeads\\V1\\GPBMetadata\xea\x02\rBobobeads::V1b\x06proto3"

var (
	file_template_proto_rawDescOnce sync.Once
	file_template_proto_rawDescData []byte
)

func file_template_proto_rawDescGZIP() []byte {
	file_template_proto_rawDescOnce.Do(func() {
		file_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_template_proto_rawDesc), len(file_template_proto_rawDesc)))
	})
	return file_template_proto_rawDescData
}

var file_template_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_template_proto_goTypes = []any{
	(*CategoryItem)(nil),                   // 0: bobobeads.v1.CategoryItem
	(*TemplateItem)(nil),                   // 1: bobobeads.v1.TemplateItem
	(*ListCategoriesRequest)(nil),          // 2: bobobeads.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),         // 3: bobobeads.v1.ListCategoriesResponse
	(*ListTemplatesRequest)(nil),           // 4: bobobeads.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),          // 5: bobobeads.v1.ListTemplatesResponse
	(*GetTemplateRequest)(nil),             // 6: bobobeads.v1.GetTemplateRequest
	(*GetTemplateResponse)(nil),            // 7: bobobeads.v1.GetTemplateResponse
	(*FavoriteTemplateRequest)(nil),        // 8: bobobeads.v1.FavoriteTemplateRequest
	(*FavoriteTemplateResponse)(nil),       // 9: bobobeads.v1.FavoriteTemplateResponse
	(*UnfavoriteTemplateRequest)(nil),      // 10: bobobeads.v1.UnfavoriteTemplateRequest
	(*UnfavoriteTemplateResponse)(nil),     // 11: bobobeads.v1.UnfavoriteTemplateResponse
	(*ListFavoriteTemplatesRequest)(nil),   // 12: bobobeads.v1.ListFavoriteTemplatesRequest
	(*ListFavoriteTemplatesResponse)(nil),  // 13: bobobeads.v1.ListFavoriteTemplatesResponse
	(*ListFavoriteCategoriesRequest)(nil),  // 14: bobobeads.v1.ListFavoriteCategoriesRequest
	(*ListFavoriteCategoriesResponse)(nil), // 15: bobobeads.v1.ListFavoriteCategoriesResponse
	(*RandomTemplateRequest)(nil),          // 16: bobobeads.v1.RandomTemplateRequest
	(*RandomTemplateResponse)(nil),         // 17: bobobeads.v1.RandomTemplateResponse
	(*BlindBoxQuota)(nil),                  // 18: bobobeads.v1.BlindBoxQuota
	(*GetBlindBoxQuotaRequest)(nil),        // 19: bobobeads.v1.GetBlindBoxQuotaRequest
	(*GetBlindBoxQuotaResponse)(nil),       // 20: bobobeads.v1.GetBlindBoxQuotaResponse
	(*ListBlindBoxRecordsRequest)(nil),     // 21: bobobeads.v1.ListBlindBoxRecordsRequest
	(*ListBlindBoxRecordsResponse)(nil),    // 22: bobobeads.v1.ListBlindBoxRecordsResponse
	(*RequestHeader)(nil),                  // 23: bobobeads.v1.RequestHeader
	(*ResponseHeader)(nil),                 // 24: bobobeads.v1.ResponseHeader
	(*PageRequest)(nil),                    // 25: bobobeads.v1.PageRequest
	(*PageResponse)(nil),                   // 26: bobobeads.v1.PageResponse
	(*PatternData)(nil),                    // 27: bobobeads.v1.PatternData
}
var file_template_proto_depIdxs = []int32{
	23, // 0: bobobeads.v1.ListCategoriesRequest.header:type_name -> bobobeads.v1.RequestHeader
	24, // 1: bobobeads.v1.ListCategoriesResponse.header:type_name -> bobobeads.v1.ResponseHeader
	0,  // 2: bobobeads.v1.ListCategoriesResponse.categories:type_name -> bobobeads.v1.CategoryItem
	23, // 3: bobobeads.v1.ListTemplatesRequest.header:type_name -> bobobeads.v1.RequestHeader
	25, // 4: bobobeads.v1.ListTemplatesRequest.page:type_name -> bobobeads.v1.PageRequest
	24, // 5: bobobeads.v1.ListTemplatesResponse.header:type_name -> bobobeads.v1.ResponseHeader
	1,  // 6: bobobeads.v1.ListTemplatesResponse.templates:type_name -> bobobeads.v1.TemplateItem
	26, // 7: bobobeads.v1.ListTemplatesResponse.page:type_name -> bobobeads.v1.PageResponse
	23, // 8: bobobeads.v1.GetTemplateRequest.header:type_name -> bobobeads.v1.RequestHeader
	24, // 9: bobobeads.v1.GetTemplateResponse.header:type_name -> bobobeads.v1.ResponseHeader
	1,  // 10: bobobeads.v1.GetTemplateResponse.template:type_name -> bobobeads.v1.TemplateItem
	27, // 11: bobobeads.v1.GetTemplateResponse.pattern_data:type_name -> bobobeads.v1.PatternData
	23, // 12: bobobeads.v1.FavoriteTemplateRequest.header:type_name -> bobobeads.v1.RequestHeader
	24, // 13: bobobeads.v1.FavoriteTemplateResponse.header:type_name -> bobobeads.v1.ResponseHeader
	23, // 14: bobobeads.v1.UnfavoriteTemplateRequest.header:type_name -> bobobeads.v1.RequestHeader
	24, // 15: bobobeads.v1.UnfavoriteTemplateResponse.header:type_name -> bobobeads.v1.ResponseHeader
	23, // 16: bobobeads.v1.ListFavoriteTemplatesRequest.header:type_name -> bobobeads.v1.RequestHeader
	25, // 17: bobobeads.v1.ListFavoriteTemplatesRequest.page:type_name -> bobobeads.v1.PageRequest
	24, // 18: bobobeads.v1.ListFavoriteTemplatesResponse.header:type_name -> bobobeads.v1.ResponseHeader
	1,  // 19: bobobeads.v1.ListFavoriteTemplatesResponse.templates:type_name -> bobobeads.v1.TemplateItem
	26, // 20: bobobeads.v1.ListFavoriteTemplatesResponse.page:type_name -> bobobeads.v1.PageResponse
	23, // 21: bobobeads.v1.ListFavoriteCategoriesRequest.header:type_name -> bobobeads.v1.RequestHeader
	24, // 22: bobobeads.v1.ListFavoriteCategoriesResponse.header:type_name -> bobobeads.v1.ResponseHeader
	0,  // 23: bobobeads.v1.ListFavoriteCategoriesResponse.categories:type_name -> bobobeads.v1.CategoryItem
	23, // 24: bobobeads.v1.RandomTemplateRequest.header:type_name -> bobobeads.v1.RequestHeader
	24, // 25: bobobeads.v1.RandomTemplateResponse.header:type_name -> bobobeads.v1.ResponseHeader
	1,  // 26: bobobeads.v1.RandomTemplateResponse.template:type_name -> bobobeads.v1.TemplateItem
	27, // 27: bobobeads.v1.RandomTemplateResponse.pattern_data:type_name -> bobobeads.v1.PatternData
	18, // 28: bobobeads.v1.RandomTemplateResponse.quota:type_name -> bobobeads.v1.BlindBoxQuota
	23, // 29: bobobeads.v1.GetBlindBoxQuotaRequest.header:type_name -> bobobeads.v1.RequestHeader
	24, // 30: bobobeads.v1.GetBlindBoxQuotaResponse.header:type_name -> bobobeads.v1.ResponseHeader
	18, // 31: bobobeads.v1.GetBlindBoxQuotaResponse.quota:type_name -> bobobeads.v1.BlindBoxQuota
	23, // 32: bobobeads.v1.ListBlindBoxRecordsRequest.header:type_name -> bobobeads.v1.RequestHeader
	25, // 33: bobobeads.v1.ListBlindBoxRecordsRequest.page:type_name -> bobobeads.v1.PageRequest
	24, // 34: bobobeads.v1.ListBlindBoxRecordsResponse.header:type_name -> bobobeads.v1.ResponseHeader
	1,  // 35: bobobeads.v1.ListBlindBoxRecordsResponse.templates:type_name -> bobobeads.v1.TemplateItem
	26, // 36: bobobeads.v1.ListBlindBoxRecordsResponse.page:type_name -> bobobeads.v1.PageResponse
	6,  // 37: bobobeads.v1.TemplateService.GetTemplate:input_type -> bobobeads.v1.GetTemplateRequest
	4,  // 38: bobobeads.v1.TemplateService.ListTemplates:input_type -> bobobeads.v1.ListTemplatesRequest
	2,  // 39: bobobeads.v1.TemplateService.ListCategories:input_type -> bobobeads.v1.ListCategoriesRequest
	12, // 40: bobobeads.v1.TemplateService.ListFavoriteTemplates:input_type -> bobobeads.v1.ListFavoriteTemplatesRequest
	14, // 41: bobobeads.v1.TemplateService.ListFavoriteCategories:input_type -> bobobeads.v1.ListFavoriteCategoriesRequest
	8,  // 42: bobobeads.v1.TemplateService.FavoriteTemplate:input_type -> bobobeads.v1.FavoriteTemplateRequest
	10, // 43: bobobeads.v1.TemplateService.UnfavoriteTemplate:input_type -> bobobeads.v1.UnfavoriteTemplateRequest
	16, // 44: bobobeads.v1.TemplateService.RandomTemplate:input_type -> bobobeads.v1.RandomTemplateRequest
	21, // 45: bobobeads.v1.TemplateService.ListBlindBoxRecords:input_type -> bobobeads.v1.ListBlindBoxRecordsRequest
	19, // 46: bobobeads.v1.TemplateService.GetBlindBoxQuota:input_type -> bobobeads.v1.GetBlindBoxQuotaRequest
	7,  // 47: bobobeads.v1.TemplateService.GetTemplate:output_type -> bobobeads.v1.GetTemplateResponse
	5,  // 48: bobobeads.v1.TemplateService.ListTemplates:output_type -> bobobeads.v1.ListTemplatesResponse
	3,  // 49: bobobeads.v1.TemplateService.ListCategories:output_type -> bobobeads.v1.ListCategoriesResponse
	13, // 50: bobobeads.v1.TemplateService.ListFavoriteTemplates:output_type -> bobobeads.v1.ListFavoriteTemplatesResponse
	15, // 51: bobobeads.v1.TemplateService.ListFavoriteCategories:output_type -> bobobeads.v1.ListFavoriteCategoriesResponse
	9,  // 52: bobobeads.v1.TemplateService.FavoriteTemplate:output_type -> bobobeads.v1.FavoriteTemplateResponse
	11, // 53: bobobeads.v1.TemplateService.UnfavoriteTemplate:output_type -> bobobeads.v1.UnfavoriteTemplateResponse
	17, // 54: bobobeads.v1.TemplateService.RandomTemplate:output_type -> bobobeads.v1.RandomTemplateResponse
	22, // 55: bobobeads.v1.TemplateService.ListBlindBoxRecords:output_type -> bobobeads.v1.ListBlindBoxRecordsResponse
	20, // 56: bobobeads.v1.TemplateService.GetBlindBoxQuota:output_type -> bobobeads.v1.GetBlindBoxQuotaResponse
	47, // [47:57] is the sub-list for method output_type
	37, // [37:47] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_template_proto_init() }
func file_template_proto_init() {
	if File_template_proto != nil {
		return
	}
	file_common_proto_init()
	file_work_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_template_proto_rawDesc), len(file_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_template_proto_goTypes,
		DependencyIndexes: file_template_proto_depIdxs,
		MessageInfos:      file_template_proto_msgTypes,
	}.Build()
	File_template_proto = out.File
	file_template_proto_goTypes = nil
	file_template_proto_depIdxs = nil
}
