// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header        *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type GetUserInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 用户信息。
	User *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// 当前积分余额。
	CreditBalance int32 `protobuf:"varint,3,opt,name=credit_balance,json=creditBalance,proto3" json:"credit_balance,omitempty"`
	// 今日剩余免费次数。
	DailyFreeRemaining int32 `protobuf:"varint,4,opt,name=daily_free_remaining,json=dailyFreeRemaining,proto3" json:"daily_free_remaining,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetUserInfoResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserInfoResponse) GetCreditBalance() int32 {
	if x != nil {
		return x.CreditBalance
	}
	return 0
}

func (x *GetUserInfoResponse) GetDailyFreeRemaining() int32 {
	if x != nil {
		return x.DailyFreeRemaining
	}
	return 0
}

type UpdateUserInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 用户昵称。
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 头像地址。
	AvatarUrl     string `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserInfoRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpdateUserInfoRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateUserInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header        *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoResponse) Reset() {
	*x = UpdateUserInfoResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoResponse) ProtoMessage() {}

func (x *UpdateUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserInfoResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type BindPhoneRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// 手机号。
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	// 短信验证码。
	Code          string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPhoneRequest) Reset() {
	*x = BindPhoneRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPhoneRequest) ProtoMessage() {}

func (x *BindPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPhoneRequest.ProtoReflect.Descriptor instead.
func (*BindPhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *BindPhoneRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BindPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *BindPhoneRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type BindPhoneResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header        *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPhoneResponse) Reset() {
	*x = BindPhoneResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPhoneResponse) ProtoMessage() {}

func (x *BindPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPhoneResponse.ProtoReflect.Descriptor instead.
func (*BindPhoneResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *BindPhoneResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type DeleteAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求公共头。
	Header        *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAccountRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type DeleteAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应公共头。
	Header        *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAccountResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\fbobobeads.v1\x1a\fcommon.proto\x1a\n" +
	"auth.proto\x1a\x1cgoogle/api/annotations.proto\"I\n" +
	"\x12GetUserInfoRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"\xd0\x01\n" +
	"\x13GetUserInfoResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\x12*\n" +
	"\x04user\x18\x02 \x01(\v2\x16.bobobeads.v1.UserInfoR\x04user\x12%\n" +
	"\x0ecredit_balance\x18\x03 \x01(\x05R\rcreditBalance\x120\n" +
	"\x14daily_free_remaining\x18\x04 \x01(\x05R\x12dailyFreeRemaining\"\x87\x01\n" +
	"\x15UpdateUserInfoRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"N\n" +
	"\x16UpdateUserInfoResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\"q\n" +
	"\x10BindPhoneRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"I\n" +
	"\x11BindPhoneResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header\"K\n" +
	"\x14DeleteAccountRequest\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.bobobeads.v1.RequestHeaderR\x06header\"M\n" +
	"\x15DeleteAccountResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.bobobeads.v1.ResponseHeaderR\x06header2\xe1\x03\n" +
	"\vUserService\x12m\n" +
	"\vGetUserInfo\x12 .bobobeads.v1.GetUserInfoRequest\x1a!.bobobeads.v1.GetUserInfoResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/user/info\x12y\n" +
	"\x0eUpdateUserInfo\x12#.bobobeads.v1.UpdateUserInfoRequest\x1a$.bobobeads.v1.UpdateUserInfoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/v1/user/info\x12p\n" +
	"\tBindPhone\x12\x1e.bobobeads.v1.BindPhoneRequest\x1a\x1f.bobobeads.v1.BindPhoneResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/user/bind-phone\x12v\n" +
	"\rDeleteAccount\x12\".bobobeads.v1.DeleteAccountRequest\x1a#.bobobeads.v1.DeleteAccountResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/v1/user/accountB\xa1\x01\n" +
	"\x10com.bobobeads.v1B\tUserProtoP\x01Z1github.com/zhaojiabo/bobobeads_server/internal/pb\xa2\x02\x03BXX\xaa\x02\fBobobeads.V1\xca\x02\fBobobeads\\V1\xe2\x02\x18Bobobeads\\V1\\GPBMetadata\xea\x02\rBobobeads::V1b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_proto_goTypes = []any{
	(*GetUserInfoRequest)(nil),     // 0: bobobeads.v1.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),    // 1: bobobeads.v1.GetUserInfoResponse
	(*UpdateUserInfoRequest)(nil),  // 2: bobobeads.v1.UpdateUserInfoRequest
	(*UpdateUserInfoResponse)(nil), // 3: bobobeads.v1.UpdateUserInfoResponse
	(*BindPhoneRequest)(nil),       // 4: bobobeads.v1.BindPhoneRequest
	(*BindPhoneResponse)(nil),      // 5: bobobeads.v1.BindPhoneResponse
	(*DeleteAccountRequest)(nil),   // 6: bobobeads.v1.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),  // 7: bobobeads.v1.DeleteAccountResponse
	(*RequestHeader)(nil),          // 8: bobobeads.v1.RequestHeader
	(*ResponseHeader)(nil),         // 9: bobobeads.v1.ResponseHeader
	(*UserInfo)(nil),               // 10: bobobeads.v1.UserInfo
}
var file_user_proto_depIdxs = []int32{
	8,  // 0: bobobeads.v1.GetUserInfoRequest.header:type_name -> bobobeads.v1.RequestHeader
	9,  // 1: bobobeads.v1.GetUserInfoResponse.header:type_name -> bobobeads.v1.ResponseHeader
	10, // 2: bobobeads.v1.GetUserInfoResponse.user:type_name -> bobobeads.v1.UserInfo
	8,  // 3: bobobeads.v1.UpdateUserInfoRequest.header:type_name -> bobobeads.v1.RequestHeader
	9,  // 4: bobobeads.v1.UpdateUserInfoResponse.header:type_name -> bobobeads.v1.ResponseHeader
	8,  // 5: bobobeads.v1.BindPhoneRequest.header:type_name -> bobobeads.v1.RequestHeader
	9,  // 6: bobobeads.v1.BindPhoneResponse.header:type_name -> bobobeads.v1.ResponseHeader
	8,  // 7: bobobeads.v1.DeleteAccountRequest.header:type_name -> bobobeads.v1.RequestHeader
	9,  // 8: bobobeads.v1.DeleteAccountResponse.header:type_name -> bobobeads.v1.ResponseHeader
	0,  // 9: bobobeads.v1.UserService.GetUserInfo:input_type -> bobobeads.v1.GetUserInfoRequest
	2,  // 10: bobobeads.v1.UserService.UpdateUserInfo:input_type -> bobobeads.v1.UpdateUserInfoRequest
	4,  // 11: bobobeads.v1.UserService.BindPhone:input_type -> bobobeads.v1.BindPhoneRequest
	6,  // 12: bobobeads.v1.UserService.DeleteAccount:input_type -> bobobeads.v1.DeleteAccountRequest
	1,  // 13: bobobeads.v1.UserService.GetUserInfo:output_type -> bobobeads.v1.GetUserInfoResponse
	3,  // 14: bobobeads.v1.UserService.UpdateUserInfo:output_type -> bobobeads.v1.UpdateUserInfoResponse
	5,  // 15: bobobeads.v1.UserService.BindPhone:output_type -> bobobeads.v1.BindPhoneResponse
	7,  // 16: bobobeads.v1.UserService.DeleteAccount:output_type -> bobobeads.v1.DeleteAccountResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_common_proto_init()
	file_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
